# Generated by Django 5.1.15 on 2026-07-24 17:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0006_placementrecommendation_final_curriculum'),
        ('intervention_sessions', '0002_session_accuracy_denominator_and_more'),
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('definition', models.TextField()),
                ('skill_band', models.CharField(blank=True, max_length=80)),
                ('target_date', models.DateField(blank=True, db_index=True, null=True)),
                ('achieved_date', models.DateField(blank=True, db_index=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In progress'), ('achieved', 'Achieved'), ('revised', 'Revised')], db_index=True, default='planned', max_length=20)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructional_milestones', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructional_milestones', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['target_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dimension', models.CharField(choices=[('methodology', 'Methodology'), ('grade_band', 'Grade band'), ('center', 'Center'), ('period', 'Period')], db_index=True, max_length=24)),
                ('dimension_value', models.CharField(help_text='Aggregate cohort label only; never store a child or staff identifier.', max_length=120)),
                ('metric_name', models.CharField(db_index=True, max_length=120)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('cohort_size', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5)])),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_aggregates', to='schools.school')),
            ],
            options={
                'ordering': ['-period_end', 'center', 'dimension', 'metric_name'],
            },
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('estimated_sessions', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_date', models.DateField(blank=True, null=True)),
                ('confidence', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_version', models.CharField(max_length=80)),
                ('evidence', models.JSONField(default=dict, help_text='Structured input references and evidence used to produce the estimate.')),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('disclaimer', models.TextField(default='This estimate supports instructional planning and is not a diagnosis or a guarantee.')),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructional_predictions', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('target_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='predictions', to='decision_support.milestone')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructional_predictions', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(choices=[('three_reteach_sessions', 'Three re-teach sessions'), ('flat_accuracy', 'Flat accuracy'), ('mastery_time_outlier', 'Mastery-time outlier'), ('regression_after_mastery', 'Regression after mastery'), ('error_pattern_persistent', 'Persistent error pattern'), ('attendance_interruption', 'Attendance interruption')], db_index=True, max_length=40)),
                ('trigger_rule', models.JSONField(default=dict, help_text='Versioned rule inputs and thresholds that explain why the flag was raised.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('evidence_snapshot', models.JSONField(default=dict, help_text='Immutable instructional evidence available when the flag was raised.')),
                ('model_or_rule_version', models.CharField(max_length=80)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_instructional_flags', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructional_flags', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructional_flags', to='curriculum.curriculumsequence')),
                ('related_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructional_flags', to='intervention_sessions.session')),
                ('routed_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routed_instructional_flags', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at', '-created_at'],
                'indexes': [models.Index(fields=['center', 'status', 'raised_at'], name='decision_su_center__21ad55_idx'), models.Index(fields=['center', 'code', 'status'], name='decision_su_center__5e934a_idx'), models.Index(fields=['child', 'status', 'raised_at'], name='decision_su_child_i_6593f5_idx'), models.Index(fields=['related_session', 'code'], name='decision_su_related_3ddb3b_idx'), models.Index(fields=['curriculum_position', 'status'], name='decision_su_curricu_787213_idx'), models.Index(fields=['is_deleted', 'created_at'], name='decision_su_is_dele_babdec_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('related_session__isnull', False), ('curriculum_position__isnull', False), _connector='OR'), name='flag_has_session_or_position')],
            },
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['center', 'status', 'target_date'], name='decision_su_center__3b85af_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['child', 'status', 'target_date'], name='decision_su_child_i_645440_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['curriculum_position', 'status'], name='decision_su_curricu_6a6930_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['is_deleted', 'created_at'], name='decision_su_is_dele_03857e_idx'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('curriculum_position__isnull', False), ('skill_band', '')), models.Q(('curriculum_position__isnull', True), models.Q(('skill_band', ''), _negated=True)), _connector='OR'), name='milestone_has_position_xor_skill_band'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(('target_date__isnull', False), ('achieved_date__isnull', False), _connector='OR'), name='milestone_has_target_or_achieved_date'),
        ),
        migrations.AddConstraint(
            model_name='milestone',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'achieved'), _negated=True), ('achieved_date__isnull', False), _connector='OR'), name='achieved_milestone_has_date'),
        ),
        migrations.AddIndex(
            model_name='outcomeaggregate',
            index=models.Index(fields=['center', 'period_start', 'period_end'], name='decision_su_center__c288fd_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeaggregate',
            index=models.Index(fields=['center', 'dimension', 'metric_name'], name='decision_su_center__c33f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeaggregate',
            index=models.Index(fields=['dimension', 'dimension_value', 'period_end'], name='decision_su_dimensi_464e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeaggregate',
            index=models.Index(fields=['metric_name', 'period_end'], name='decision_su_metric__d8ff23_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomeaggregate',
            index=models.Index(fields=['is_deleted', 'created_at'], name='decision_su_is_dele_8fa976_idx'),
        ),
        migrations.AddConstraint(
            model_name='outcomeaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('cohort_size__gte', 5)), name='outcome_cohort_meets_privacy_floor'),
        ),
        migrations.AddConstraint(
            model_name='outcomeaggregate',
            constraint=models.CheckConstraint(condition=models.Q(('period_end__gte', models.F('period_start'))), name='outcome_period_end_on_or_after_start'),
        ),
        migrations.AddConstraint(
            model_name='outcomeaggregate',
            constraint=models.UniqueConstraint(fields=('center', 'dimension', 'dimension_value', 'metric_name', 'period_start', 'period_end'), name='unique_outcome_metric_cohort_period'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['center', 'generated_at'], name='decision_su_center__2d95a3_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['child', 'generated_at'], name='decision_su_child_i_726bb0_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['target_position', 'generated_at'], name='decision_su_target__9f5b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['target_milestone', 'generated_at'], name='decision_su_target__a451ce_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['model_version', 'generated_at'], name='decision_su_model_v_460ad5_idx'),
        ),
        migrations.AddIndex(
            model_name='prediction',
            index=models.Index(fields=['is_deleted', 'created_at'], name='decision_su_is_dele_c2fed1_idx'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_milestone__isnull', False), ('target_position__isnull', True)), models.Q(('target_milestone__isnull', True), ('target_position__isnull', False)), _connector='OR'), name='prediction_has_one_target'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estimated_sessions__isnull', False), ('estimated_date__isnull', True)), models.Q(('estimated_sessions__isnull', True), ('estimated_date__isnull', False)), _connector='OR'), name='prediction_has_one_estimate'),
        ),
        migrations.AddConstraint(
            model_name='prediction',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 1)), name='prediction_confidence_between_0_and_1'),
        ),
    ]
