# Generated by Django 5.1.15 on 2026-07-24 17:43

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_placementrecommendation_final_curriculum'),
        ('decision_support', '0001_initial'),
        ('intervention_sessions', '0002_session_accuracy_denominator_and_more'),
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowthFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('flag_code', models.CharField(choices=[('three_reteach_sessions', 'Three consecutive re-teach sessions'), ('flat_accuracy', 'Flat accuracy'), ('mastery_time_outlier', 'Mastery-time review'), ('regression_after_mastery', 'Retention review after mastery'), ('error_pattern_persistent', 'Persistent error pattern'), ('attendance_interruption', 'Attendance interruption')], db_index=True, max_length=40)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=12)),
                ('evidence_snapshot', models.JSONField(default=dict)),
                ('explanation', models.TextField()),
                ('advisory_recommendation', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('opened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_growth_flags', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_flags', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='growth_flags', to='curriculum.curriculumsequence')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_growth_flags', to=settings.AUTH_USER_MODEL)),
                ('routed_to', models.ManyToManyField(blank=True, related_name='routed_growth_flags', to=settings.AUTH_USER_MODEL)),
                ('trigger_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_growth_flags', to='intervention_sessions.session')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at', '-created_at'],
                'indexes': [models.Index(fields=['center', 'status', 'severity'], name='decision_su_center__5191c0_idx'), models.Index(fields=['child', 'status', 'opened_at'], name='decision_su_child_i_2049a0_idx'), models.Index(fields=['position', 'flag_code', 'status'], name='decision_su_positio_f1eac1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'open')), fields=('child', 'position', 'flag_code'), name='unique_open_growth_flag')],
            },
        ),
        migrations.CreateModel(
            name='MilestonePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('target_label', models.CharField(max_length=255)),
                ('predicted_sessions', models.PositiveIntegerField()),
                ('predicted_date', models.DateField()),
                ('lower_bound_sessions', models.PositiveIntegerField()),
                ('upper_bound_sessions', models.PositiveIntegerField()),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], db_index=True, max_length=12)),
                ('evidence_summary', models.JSONField(default=dict)),
                ('explanation', models.TextField()),
                ('parent_timeline', models.TextField()),
                ('disclaimer', models.TextField(default='This is an instructional planning estimate based on recent progress and attendance. It may change and is not a guarantee.')),
                ('engine_version', models.CharField(default='deterministic-2026.1', max_length=40)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_predictions', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='milestone_predictions', to='curriculum.studentplacement')),
                ('target_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='milestone_predictions', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['center', 'is_current', 'generated_at'], name='decision_su_center__cf9a36_idx'), models.Index(fields=['child', 'is_current'], name='decision_su_child_i_05c054_idx'), models.Index(fields=['target_position', 'predicted_date'], name='decision_su_target__03d9c6_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True), ('is_deleted', False)), fields=('child',), name='unique_current_milestone_prediction')],
            },
        ),
    ]
