# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('emerging', 'Emerging'), ('developing', 'Developing'), ('proficient', 'Proficient'), ('mastered', 'Mastered')], db_index=True, default='not_started', max_length=32)),
                ('current_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('target_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['child__last_name', 'skill__code'],
            },
        ),
        migrations.CreateModel(
            name='MasteryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mastered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_records', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-mastered_at'],
            },
        ),
    ]
