# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_initial'),
        ('curriculum', '0001_initial'),
        ('progress', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='masteryrecord',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='masteryrecord',
            name='mastered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mastery_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='masteryrecord',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='curriculum.skill'),
        ),
        migrations.AddField(
            model_name='progress',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='progress',
            name='last_assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='progress',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_records', to='schools.school'),
        ),
        migrations.AddField(
            model_name='progress',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='curriculum.skill'),
        ),
        migrations.AddField(
            model_name='masteryrecord',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mastery_records', to='progress.progress'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['child', 'status'], name='progress_pr_child_i_dd0c73_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['skill', 'status'], name='progress_pr_skill_i_75a7ad_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['school', 'status'], name='progress_pr_school__0694a5_idx'),
        ),
        migrations.AddIndex(
            model_name='progress',
            index=models.Index(fields=['is_deleted', 'created_at'], name='progress_pr_is_dele_a6a6e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='progress',
            constraint=models.UniqueConstraint(fields=('child', 'skill'), name='unique_child_skill_progress'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['child', 'mastered_at'], name='progress_ma_child_i_05ab4f_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['skill', 'mastered_at'], name='progress_ma_skill_i_c7fd50_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['progress', 'mastered_at'], name='progress_ma_progres_fa0c76_idx'),
        ),
        migrations.AddIndex(
            model_name='masteryrecord',
            index=models.Index(fields=['is_deleted', 'created_at'], name='progress_ma_is_dele_00247e_idx'),
        ),
    ]
