# ruff: noqa: RUF012
# Generated by Django 5.1.15 on 2026-09-14 14:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("crm", "0008_alter_formsubmission_form_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkerHeartbeat",
            fields=[
                (
                    "name",
                    models.CharField(
                        default="email",
                        max_length=30,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("last_seen_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Authorization",
            fields=[
                (
                    "state_hash",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("session_hash", models.CharField(max_length=64)),
                ("encrypted_verifier", models.TextField()),
                ("nonce", models.CharField(max_length=128)),
                ("expires_at", models.DateTimeField()),
                ("consumed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("subject", models.CharField(max_length=998)),
                ("body_html", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Mailbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("google_subject", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disconnected", "Disconnected"),
                            ("connected", "Connected"),
                            ("reconnect", "Reconnect required"),
                        ],
                        default="disconnected",
                        max_length=20,
                    ),
                ),
                ("encrypted_refresh_token", models.TextField(blank=True)),
                ("signature", models.TextField(blank=True)),
                ("history_id", models.CharField(blank=True, max_length=100)),
                ("watch_expires_at", models.DateTimeField(blank=True, null=True)),
                ("watch_renewed_at", models.DateTimeField(blank=True, null=True)),
                ("sync_requested_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("recovery_cursor", models.PositiveBigIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gmail_thread_id", models.CharField(max_length=100)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("import_pending", models.BooleanField(default=False)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_conversations",
                        to="crm.lead",
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="crm_email.mailbox",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("gmail_id", models.CharField(blank=True, max_length=100, null=True)),
                ("rfc_message_id", models.CharField(blank=True, max_length=998)),
                ("in_reply_to", models.CharField(blank=True, max_length=998)),
                ("references", models.TextField(blank=True)),
                ("reply_to", models.EmailField(blank=True, max_length=254)),
                ("sender", models.EmailField(blank=True, max_length=254)),
                ("to", models.JSONField(default=list)),
                ("cc", models.JSONField(default=list)),
                ("bcc", models.JSONField(default=list)),
                ("subject", models.CharField(max_length=998)),
                ("body_text", models.TextField(blank=True)),
                ("body_html", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("uncertain", "Checking send result"),
                            ("sent", "Sent"),
                            ("received", "Received"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("follow_up_days", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm_email.conversation",
                    ),
                ),
                (
                    "follow_up",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="crm.crmactivity",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="crm.lead"
                    ),
                ),
                (
                    "mailbox",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm_email.mailbox",
                    ),
                ),
            ],
            options={
                "ordering": ["sent_at", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("size", models.PositiveIntegerField()),
                ("encrypted_data", models.BinaryField()),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="crm_email.message",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "gmail_thread_id"), name="crm_email_thread_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.UniqueConstraint(
                fields=("mailbox", "gmail_id"), name="crm_email_message_unique"
            ),
        ),
    ]
