# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-09-14 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_recruitinginterest_candidate_pool_and_owner"),
        ("crm", "0013_websitereceipt"),
        ("crm_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="recruiting_interest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.recruitinginterest",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="crm.lead",
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("lead__isnull", False), ("recruiting_interest__isnull", True)
                    ),
                    models.Q(
                        ("lead__isnull", True), ("recruiting_interest__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="crm_email_exactly_one_contact",
            ),
        ),
    ]
