# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-09-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0020_opportunity_investment_category"),
        ("crm_email", "0002_message_recruiting_interest_alter_message_lead_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StageEmailPilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equity_signature", models.TextField(blank=True)),
                ("enabled", models.BooleanField(default=False)),
                ("scheduling_link", models.URLField(blank=True, max_length=1000)),
                (
                    "bethany_signature",
                    models.TextField(
                        default="Bethany Fleming\nFounder & CEO, ClearCode Reading Center\nbethany@clearcodereading.com"
                    ),
                ),
                (
                    "foundation_name",
                    models.CharField(default="Bethany Fleming", max_length=150),
                ),
                (
                    "sample_company",
                    models.CharField(default="Example Organization", max_length=255),
                ),
                (
                    "sample_investment_category",
                    models.CharField(blank=True, max_length=255),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "equity_mailbox",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equity_pilots",
                        to="crm_email.mailbox",
                    ),
                ),
                (
                    "mailbox",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm_email.mailbox",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StageEmailDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pipeline", models.CharField(max_length=32)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("cancelled", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crm.opportunity",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_delivery",
                        to="crm_email.message",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="crm_email.stageemailpilot",
                    ),
                ),
            ],
        ),
    ]
