# Generated by Django 5.2.17 on 2026-09-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm_email", "0003_stageemailpilot_stageemaildelivery"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=60, unique=True)),
                ("subject", models.CharField(blank=True, max_length=998)),
                ("heading", models.CharField(blank=True, max_length=255)),
                ("body", models.TextField(blank=True)),
                ("next_step", models.TextField(blank=True)),
                ("action_label", models.CharField(blank=True, max_length=120)),
                ("action_url", models.CharField(blank=True, max_length=1000)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
    ]
