# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm_email", "0006_bethany_signature"),
        ("crm_email", "0006_stageemaildelivery_lead"),
    ]

    operations = []
