# Generated by Django 5.1.15 on 2026-09-14 14:51
import uuid
from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Asset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("content_type", models.CharField(max_length=100)),
                ("size", models.PositiveIntegerField()),
                ("digest", models.CharField(db_index=True, max_length=64)),
                ("data", models.BinaryField()),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slug", models.SlugField(max_length=180)),
                ("publish_at", models.DateTimeField(blank=True, null=True)),
                ("archived", models.BooleanField(db_index=True, default=False)),
                ("submitted", models.BooleanField(db_index=True, default=False)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "permissions": [
                    ("publish_resource", "Can review and publish website resources")
                ],
            },
        ),
        migrations.CreateModel(
            name="Revision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "title",
                    models.CharField(default="Untitled resource", max_length=200),
                ),
                ("description", models.CharField(blank=True, max_length=320)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("link", "Link or video"),
                            ("article", "Article"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("families", "Families"),
                            ("educators", "Educators"),
                            ("both", "Families and educators"),
                        ],
                        default="families",
                        max_length=12,
                    ),
                ),
                ("body", models.TextField(blank=True, max_length=100000)),
                ("url", models.URLField(blank=True, max_length=2000)),
                ("cover_alt", models.CharField(blank=True, max_length=240)),
                ("grade", models.CharField(blank=True, max_length=80)),
                ("language", models.CharField(default="English", max_length=60)),
                (
                    "access",
                    models.CharField(
                        choices=[
                            ("family", "Family registration required"),
                            ("public", "Everyone (public)"),
                        ],
                        default="family",
                        max_length=12,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("seo_title", models.CharField(blank=True, max_length=70)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="file_revisions",
                        to="resources.asset",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cover",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cover_revisions",
                        to="resources.asset",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="resources.resource",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resources.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ResourceEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="resources.resource",
                    ),
                ),
                (
                    "revision",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="resources.revision",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="draft",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="resources.revision",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="live",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="resources.revision",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="scheduled",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="resources.revision",
            ),
        ),
        migrations.CreateModel(
            name="UploadBatch",
            fields=[
                ("token", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("resources", models.ManyToManyField(to="resources.resource")),
            ],
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("publish_at__isnull", True), ("scheduled__isnull", True)),
                    models.Q(
                        ("publish_at__isnull", False), ("scheduled__isnull", False)
                    ),
                    _connector="OR",
                ),
                name="resource_schedule_has_time",
            ),
        ),
    ]
