from typing import ClassVar

# Generated by Django 5.1.15 on 2026-09-14 15:00
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("resources", "0002_initial_topics"),
    ]

    operations: ClassVar = [
        migrations.AddField(
            model_name="asset",
            name="preview",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="resources.asset",
            ),
        ),
    ]
