from typing import ClassVar

# Generated by Django 5.1.15 on 2026-09-14 15:02
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies: ClassVar = [
        ("resources", "0003_asset_preview"),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name="StaffSetupToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("digest", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
