# Generated by Django 5.1.15 on 2026-07-24 17:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeIdentifiedOutcomeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_key', models.CharField(db_index=True, max_length=64)),
                ('methodology', models.CharField(db_index=True, max_length=40)),
                ('grade_band', models.CharField(db_index=True, max_length=32)),
                ('window_type', models.CharField(choices=[('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year'), ('custom', 'Custom')], db_index=True, max_length=16)),
                ('window_start', models.DateField(db_index=True)),
                ('window_end', models.DateField(db_index=True)),
                ('metric_scope', models.CharField(db_index=True, default='core_outcomes', max_length=40)),
                ('aggregate_version', models.CharField(db_index=True, default='v1', max_length=32)),
                ('privacy_floor', models.PositiveSmallIntegerField(default=5)),
                ('metrics', models.JSONField(default=dict)),
                ('source_counts', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outcome_snapshots', to='schools.school')),
            ],
            options={
                'ordering': ['-window_end', 'center_key', 'methodology', 'grade_band', '-generated_at'],
                'indexes': [models.Index(fields=['center', 'window_type', 'window_end'], name='outcomes_de_center__6c72a3_idx'), models.Index(fields=['methodology', 'grade_band', 'window_end'], name='outcomes_de_methodo_b450b8_idx'), models.Index(fields=['metric_scope', 'aggregate_version'], name='outcomes_de_metric__39a414_idx')],
                'constraints': [models.UniqueConstraint(fields=('center', 'methodology', 'grade_band', 'window_type', 'window_start', 'window_end', 'metric_scope', 'aggregate_version'), name='unique_outcome_snapshot_version')],
            },
        ),
    ]
