# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(choices=[('phonological_awareness', 'Phonological Awareness'), ('phonics', 'Phonics'), ('fluency', 'Fluency'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension'), ('writing', 'Writing')], db_index=True, max_length=40)),
                ('grade_band', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks', to='curriculum.skill')),
            ],
            options={
                'ordering': ['domain', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('grade_level', models.CharField(blank=True, db_index=True, max_length=64)),
                ('duration_minutes', models.PositiveIntegerField(default=20)),
                ('objective', models.TextField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('materials', models.JSONField(blank=True, default=list)),
                ('differentiation', models.JSONField(blank=True, default=dict)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='curriculum.skill')),
            ],
            options={
                'ordering': ['skill__code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TeachingAid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('aid_type', models.CharField(choices=[('worksheet', 'Worksheet'), ('slide_deck', 'Slide Deck'), ('manipulative', 'Manipulative'), ('decodable_text', 'Decodable Text'), ('assessment_prompt', 'Assessment Prompt'), ('other', 'Other')], db_index=True, max_length=32)),
                ('file', models.FileField(blank=True, upload_to='teaching-aids/%Y/%m/%d/')),
                ('url', models.URLField(blank=True)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_aids', to='curriculum.lesson')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teaching_aids', to='curriculum.skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['code'], name='curriculum__code_ddc6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['domain', 'grade_band'], name='curriculum__domain_03f577_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_704dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['slug'], name='curriculum__slug_b66c8d_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['skill', 'is_published'], name='curriculum__skill_i_32451f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['grade_level', 'is_published'], name='curriculum__grade_l_c84f18_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_ce5ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingaid',
            index=models.Index(fields=['lesson', 'aid_type'], name='curriculum__lesson__e7efd2_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingaid',
            index=models.Index(fields=['skill', 'aid_type'], name='curriculum__skill_i_741fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='teachingaid',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_736950_idx'),
        ),
    ]
