# Generated by Django 5.1.15 on 2026-05-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LessonTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=160, unique=True)),
                ("grade_band", models.CharField(blank=True, db_index=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("goal", models.CharField(blank=True, max_length=255)),
                ("recommended_minutes", models.PositiveIntegerField(default=15)),
                ("activities", models.JSONField(blank=True, default=list)),
                ("materials", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "skill",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lesson_templates",
                        to="curriculum.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="TeacherLessonTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="template_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        limit_choices_to={"role": "teacher"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_lesson_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_assignments",
                        to="curriculum.lessontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["teacher__last_name", "template__title"],
            },
        ),
        migrations.CreateModel(
            name="ChildLessonAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("paused", "Paused"),
                        ],
                        db_index=True,
                        default="assigned",
                        max_length=32,
                    ),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("teacher_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_lesson_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lesson_assignments",
                        to="users.childprofile",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="child_assignments",
                        to="curriculum.lessontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["status", "due_date", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="lessontemplate",
            index=models.Index(fields=["slug"], name="curriculum__slug_6e82c4_idx"),
        ),
        migrations.AddIndex(
            model_name="lessontemplate",
            index=models.Index(fields=["grade_band", "is_active"], name="curriculum__grade_b_558d38_idx"),
        ),
        migrations.AddIndex(
            model_name="lessontemplate",
            index=models.Index(fields=["skill", "is_active"], name="curriculum__skill_i_25de5c_idx"),
        ),
        migrations.AddIndex(
            model_name="lessontemplate",
            index=models.Index(fields=["is_deleted", "created_at"], name="curriculum__is_dele_887247_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherlessontemplate",
            index=models.Index(fields=["teacher", "is_deleted"], name="curriculum__teacher_52f736_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherlessontemplate",
            index=models.Index(fields=["template", "is_deleted"], name="curriculum__templat_8bc5d6_idx"),
        ),
        migrations.AddIndex(
            model_name="teacherlessontemplate",
            index=models.Index(fields=["is_deleted", "created_at"], name="curriculum__is_dele_680325_idx"),
        ),
        migrations.AddConstraint(
            model_name="teacherlessontemplate",
            constraint=models.UniqueConstraint(fields=("teacher", "template"), name="unique_teacher_lesson_template"),
        ),
        migrations.AddIndex(
            model_name="childlessonassignment",
            index=models.Index(fields=["child", "status"], name="curriculum__child_i_1f9b9e_idx"),
        ),
        migrations.AddIndex(
            model_name="childlessonassignment",
            index=models.Index(fields=["template", "status"], name="curriculum__templat_b1e54d_idx"),
        ),
        migrations.AddIndex(
            model_name="childlessonassignment",
            index=models.Index(fields=["assigned_by", "status"], name="curriculum__assigne_7e5bac_idx"),
        ),
        migrations.AddIndex(
            model_name="childlessonassignment",
            index=models.Index(fields=["is_deleted", "created_at"], name="curriculum__is_dele_326f31_idx"),
        ),
    ]
