# Generated by Django 5.1.15 on 2026-07-24 16:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_seed_lesson_templates'),
        ('schools', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(choices=[('pfr', 'Phonics for Reading'), ('og_plus', 'IMSE Comprehensive Orton-Gillingham Plus')], db_index=True, max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='2026.1', max_length=40)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['center__name', 'code', '-version'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('code', models.CharField(max_length=80)),
                ('sequence_order', models.PositiveIntegerField()),
                ('level', models.CharField(blank=True, choices=[('A', 'Level A'), ('B', 'Level B'), ('C', 'Level C')], db_index=True, max_length=1)),
                ('lesson_number', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('concept_number', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('position_type', models.CharField(choices=[('letter_sound', 'Letter / Sound'), ('word_type', 'Word Type'), ('syllable_type', 'Syllable Type'), ('high_frequency_word', 'High-Frequency Word'), ('phonological_awareness', 'Phonological Awareness'), ('phonics_concept', 'Phonics Concept'), ('orthographic_rule', 'Orthographic Rule'), ('morphology', 'Morphology'), ('checkpoint', 'Instructional Checkpoint')], db_index=True, max_length=32)),
                ('description', models.TextField(blank=True)),
                ('letter_sounds', models.JSONField(blank=True, default=list)),
                ('word_types', models.JSONField(blank=True, default=list)),
                ('syllable_types', models.JSONField(blank=True, default=list)),
                ('high_frequency_words', models.JSONField(blank=True, default=list)),
                ('red_words_spell_and_read', models.JSONField(blank=True, default=list)),
                ('red_words_read_only', models.JSONField(blank=True, default=list)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('item_set_schema', models.JSONField(blank=True, default=dict)),
                ('mastery_criteria', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='curriculum.curriculum')),
                ('prerequisites', models.ManyToManyField(blank=True, related_name='unlocks_positions', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curriculum', 'sequence_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('methodology_rationale', models.TextField()),
                ('placement_evidence', models.JSONField(blank=True, default=dict)),
                ('placed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_placements', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('current_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='current_student_placements', to='curriculum.curriculumsequence')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_placements', to='curriculum.curriculum')),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_placements_made', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['child__last_name', 'child__first_name', '-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentPlacementOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('rationale', models.TextField()),
                ('overridden_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('new_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_overrides_to', to='curriculum.curriculumsequence')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='override_history', to='curriculum.studentplacement')),
                ('previous_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_overrides_from', to='curriculum.curriculumsequence')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_overrides', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-overridden_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['center', 'code', 'is_active'], name='curriculum__center__57ad55_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculum',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_bb5b1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('center', 'code', 'version'), name='unique_center_curriculum_version'),
        ),
        migrations.AddIndex(
            model_name='curriculumsequence',
            index=models.Index(fields=['center', 'curriculum', 'sequence_order'], name='curriculum__center__fffe60_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumsequence',
            index=models.Index(fields=['curriculum', 'level', 'lesson_number'], name='curriculum__curricu_126f65_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumsequence',
            index=models.Index(fields=['curriculum', 'concept_number'], name='curriculum__curricu_a14632_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumsequence',
            index=models.Index(fields=['position_type', 'is_deleted'], name='curriculum__positio_c4924e_idx'),
        ),
        migrations.AddIndex(
            model_name='curriculumsequence',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_85e8d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsequence',
            constraint=models.UniqueConstraint(fields=('curriculum', 'code'), name='unique_curriculum_position_code'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsequence',
            constraint=models.UniqueConstraint(fields=('curriculum', 'sequence_order'), name='unique_curriculum_sequence_order'),
        ),
        migrations.AddConstraint(
            model_name='curriculumsequence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level', ''), ('lesson_number__isnull', True), ('concept_number__isnull', False)), models.Q(('level__in', ['A', 'B', 'C']), ('lesson_number__isnull', False), ('concept_number__isnull', True)), _connector='OR'), name='sequence_has_pfr_lesson_or_og_concept'),
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['center', 'curriculum', 'is_active'], name='curriculum__center__e3e196_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['child', 'is_active', 'is_deleted'], name='curriculum__child_i_bf1dde_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['current_position', 'is_active'], name='curriculum__current_dc8279_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacement',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_d90824_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentplacement',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('child',), name='unique_active_child_methodology'),
        ),
        migrations.AddIndex(
            model_name='studentplacementoverride',
            index=models.Index(fields=['center', 'placement', 'overridden_at'], name='curriculum__center__4ba365_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacementoverride',
            index=models.Index(fields=['specialist', 'overridden_at'], name='curriculum__special_4dea8e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentplacementoverride',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_2d7f6a_idx'),
        ),
    ]
