# Generated by Django 5.1.15 on 2026-07-24 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentaudioasset'),
        ('curriculum', '0004_curriculum_curriculumsequence_studentplacement_and_more'),
        ('schools', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentplacementoverride',
            name='evidence_considered',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='PlacementEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('instrument', models.CharField(choices=[('pfr_placement', 'PFR Placement Test'), ('og_pa_diagnostic', 'OG+ Phonological Awareness Diagnostic'), ('og_benchmark', 'OG+ Benchmark Assessment'), ('og_spelling_survey', 'OG+ Informal Spelling Survey')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('manual', 'Structured manual entry'), ('import', 'Structured import'), ('reading_survey', 'Digital Reading Survey context')], db_index=True, default='manual', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], db_index=True, default='completed', max_length=20)),
                ('assessment_version', models.CharField(max_length=80)),
                ('administered_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('instructional_grade_band', models.CharField(blank=True, db_index=True, max_length=32)),
                ('raw_results', models.JSONField(default=dict)),
                ('supporting_context', models.JSONField(blank=True, default=dict)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_evidence_administered', to=settings.AUTH_USER_MODEL)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_evidence', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_evidence', to='curriculum.curriculum')),
                ('source_assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_evidence', to='assessments.assessment')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-administered_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacementRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('decision', models.CharField(choices=[('place', 'Place at sequence position'), ('specialist_review', 'Specialist review required'), ('curriculum_complete', 'Curriculum completion review')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending specialist decision'), ('confirmed', 'Confirmed'), ('overridden', 'Overridden')], db_index=True, default='pending', max_length=20)),
                ('deficit_profile', models.JSONField(blank=True, default=list)),
                ('rule_trace', models.JSONField(default=dict)),
                ('rationale', models.TextField()),
                ('advisory_narrative', models.TextField(blank=True)),
                ('ai_metadata', models.JSONField(blank=True, default=dict)),
                ('override_rationale', models.TextField(blank=True)),
                ('evidence_considered', models.JSONField(blank=True, default=dict)),
                ('confirmed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_recommendations_confirmed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recommendation', to='curriculum.placementevidence')),
                ('final_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_placement_recommendations', to='curriculum.curriculumsequence')),
                ('recommended_curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placement_recommendations', to='curriculum.curriculum')),
                ('recommended_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placement_recommendations', to='curriculum.curriculumsequence')),
                ('resulting_placement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_recommendations', to='curriculum.studentplacement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='studentplacementoverride',
            name='source_recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='placement_overrides', to='curriculum.placementrecommendation'),
        ),
        migrations.CreateModel(
            name='RecommendedSequencePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('priority', models.PositiveSmallIntegerField()),
                ('gap_codes', models.JSONField(blank=True, default=list)),
                ('rationale', models.CharField(blank=True, max_length=500)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ranked_recommendations', to='curriculum.curriculumsequence')),
                ('recommendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_sequence', to='curriculum.placementrecommendation')),
            ],
            options={
                'ordering': ['recommendation', 'priority'],
            },
        ),
        migrations.AddIndex(
            model_name='placementevidence',
            index=models.Index(fields=['center', 'child', 'administered_at'], name='curriculum__center__53dc03_idx'),
        ),
        migrations.AddIndex(
            model_name='placementevidence',
            index=models.Index(fields=['center', 'instrument', 'status'], name='curriculum__center__d472cf_idx'),
        ),
        migrations.AddIndex(
            model_name='placementevidence',
            index=models.Index(fields=['curriculum', 'administered_at'], name='curriculum__curricu_5bf6d7_idx'),
        ),
        migrations.AddIndex(
            model_name='placementevidence',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_c58663_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecommendation',
            index=models.Index(fields=['center', 'status', 'created_at'], name='curriculum__center__7c2db7_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecommendation',
            index=models.Index(fields=['recommended_curriculum', 'recommended_position'], name='curriculum__recomme_81a493_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecommendation',
            index=models.Index(fields=['confirmed_by', 'confirmed_at'], name='curriculum__confirm_a80ccb_idx'),
        ),
        migrations.AddIndex(
            model_name='placementrecommendation',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_69cb85_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendedsequenceposition',
            index=models.Index(fields=['recommendation', 'priority'], name='curriculum__recomme_291bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='recommendedsequenceposition',
            index=models.Index(fields=['position', 'priority'], name='curriculum__positio_9d43b7_idx'),
        ),
        migrations.AddConstraint(
            model_name='recommendedsequenceposition',
            constraint=models.UniqueConstraint(fields=('recommendation', 'priority'), name='unique_recommendation_priority'),
        ),
        migrations.AddConstraint(
            model_name='recommendedsequenceposition',
            constraint=models.UniqueConstraint(fields=('recommendation', 'position'), name='unique_recommendation_position'),
        ),
    ]
