# Generated by Django 5.1.15 on 2026-07-24 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_studentplacementoverride_evidence_considered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placementrecommendation',
            name='final_curriculum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='finalized_placement_recommendations', to='curriculum.curriculum'),
        ),
    ]
