# Generated by Django 5.1.15 on 2026-07-24 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_placementrecommendation_final_curriculum'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SequencePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='active', max_length=20)),
                ('specialist_notes', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('created_from_recommendation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materialized_sequence_plan', to='curriculum.placementrecommendation')),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sequence_plans', to='curriculum.studentplacement')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SequencePlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('mastered', 'Mastered'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='curriculum.sequenceplan')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_plan_items', to='curriculum.curriculumsequence')),
            ],
            options={
                'ordering': ['plan', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SkillCrosswalk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mapping_type', models.CharField(choices=[('equivalent', 'Equivalent'), ('a_precedes_b', 'A precedes B'), ('b_precedes_a', 'B precedes A'), ('overlaps', 'Overlaps')], db_index=True, max_length=24)),
                ('equivalence', models.DecimalField(decimal_places=3, default=1, help_text='Reporting confidence from 0.000 to 1.000.', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('version', models.CharField(db_index=True, default='2026.1', max_length=40)),
                ('center', models.ForeignKey(blank=True, help_text='Leave blank for a global crosswalk within the current tenant schema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_crosswalks', to='schools.school')),
                ('skill_node_a', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crosswalks_as_a', to='curriculum.curriculumsequence')),
                ('skill_node_b', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crosswalks_as_b', to='curriculum.curriculumsequence')),
            ],
            options={
                'ordering': ['version', 'skill_node_a__code', 'skill_node_b__code'],
            },
        ),
        migrations.AddIndex(
            model_name='sequenceplan',
            index=models.Index(fields=['center', 'status', 'created_at'], name='curriculum__center__c3d33e_idx'),
        ),
        migrations.AddIndex(
            model_name='sequenceplan',
            index=models.Index(fields=['placement', 'status', 'is_deleted'], name='curriculum__placeme_fa6ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='sequenceplan',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_33b858_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequenceplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'active')), fields=('placement',), name='unique_active_sequence_plan_per_placement'),
        ),
        migrations.AddIndex(
            model_name='sequenceplanitem',
            index=models.Index(fields=['plan', 'status', 'order'], name='curriculum__plan_id_736000_idx'),
        ),
        migrations.AddIndex(
            model_name='sequenceplanitem',
            index=models.Index(fields=['position', 'status'], name='curriculum__positio_42a0a3_idx'),
        ),
        migrations.AddConstraint(
            model_name='sequenceplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'order'), name='unique_sequence_plan_item_order'),
        ),
        migrations.AddConstraint(
            model_name='sequenceplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'position'), name='unique_sequence_plan_item_position'),
        ),
        migrations.AddIndex(
            model_name='skillcrosswalk',
            index=models.Index(fields=['center', 'version', 'mapping_type'], name='curriculum__center__9c8d43_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcrosswalk',
            index=models.Index(fields=['skill_node_a', 'skill_node_b'], name='curriculum__skill_n_c03603_idx'),
        ),
        migrations.AddIndex(
            model_name='skillcrosswalk',
            index=models.Index(fields=['is_deleted', 'created_at'], name='curriculum__is_dele_54c54e_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillcrosswalk',
            constraint=models.CheckConstraint(condition=models.Q(('skill_node_a', models.F('skill_node_b')), _negated=True), name='crosswalk_nodes_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='skillcrosswalk',
            constraint=models.UniqueConstraint(condition=models.Q(('center__isnull', False)), fields=('center', 'skill_node_a', 'skill_node_b', 'mapping_type', 'version'), name='unique_center_skill_crosswalk'),
        ),
        migrations.AddConstraint(
            model_name='skillcrosswalk',
            constraint=models.UniqueConstraint(condition=models.Q(('center__isnull', True)), fields=('skill_node_a', 'skill_node_b', 'mapping_type', 'version'), name='unique_global_skill_crosswalk'),
        ),
    ]
