# Generated by Django 5.2.17 on 2026-10-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_sequenceplan_sequenceplanitem_skillcrosswalk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementevidence',
            name='instrument',
            field=models.CharField(choices=[('pfr_placement', 'PFR Placement Test'), ('og_pa_diagnostic', 'OG+ Phonological Awareness Diagnostic'), ('og_benchmark', 'OG+ Benchmark Inventory'), ('og_spelling_survey', 'OG+ Informal Spelling Survey')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='teachingaid',
            name='aid_type',
            field=models.CharField(choices=[('worksheet', 'Worksheet'), ('slide_deck', 'Slide Deck'), ('manipulative', 'Manipulative'), ('decodable_text', 'Decodable Text'), ('assessment_prompt', 'Inventory Prompt'), ('other', 'Other')], db_index=True, max_length=32),
        ),
    ]
