# Generated by Django 5.1.15 on 2026-05-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_type', models.CharField(choices=[('screening', 'Screening'), ('diagnostic', 'Diagnostic'), ('formative', 'Formative'), ('summative', 'Summative')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('human_review', 'Human Review'), ('completed', 'Completed'), ('archived', 'Archived')], db_index=True, default='pending', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('survey_completed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('max_score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('overall_score', models.IntegerField(blank=True, db_index=True, null=True)),
                ('reading_age', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4, null=True)),
                ('percentile', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('responses', models.JSONField(blank=True, default=dict)),
                ('scoring', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-scheduled_for', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('phonemic_awareness', 'Phonemic Awareness'), ('letter_sound', 'Letter Sounds'), ('phonics', 'Phonics / Decoding'), ('advanced_phonics', 'Advanced Decoding'), ('sight_words', 'Sight Words'), ('fluency', 'Fluency'), ('vocabulary', 'Vocabulary'), ('comprehension', 'Comprehension'), ('writing_readiness', 'Writing Readiness'), ('confidence', 'Reading Confidence')], db_index=True, max_length=40)),
                ('difficulty', models.CharField(choices=[('pre_reader', 'Pre-reader'), ('emerging', 'Emerging'), ('early', 'Early'), ('developing', 'Developing'), ('fluent', 'Fluent')], db_index=True, max_length=32)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('audio_prompt', 'Audio Prompt'), ('image_prompt', 'Image Prompt'), ('oral_reading', 'Oral Reading'), ('free_response', 'Free Response'), ('rating_scale', 'Rating Scale')], db_index=True, max_length=32)),
                ('question_text', models.TextField()),
                ('audio_file', models.FileField(blank=True, upload_to='assessment-audio/%Y/%m/%d/')),
                ('image_url', models.URLField(blank=True)),
                ('correct_answer', models.JSONField(blank=True, default=dict)),
                ('options', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['category', 'difficulty', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('final_scores', models.JSONField(blank=True, default=dict)),
                ('reading_age', models.DecimalField(db_index=True, decimal_places=1, max_digits=4)),
                ('grade_equivalent', models.CharField(blank=True, db_index=True, max_length=40)),
                ('category_breakdown', models.JSONField(blank=True, default=dict)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('growth_areas', models.JSONField(blank=True, default=list)),
                ('teacher_summary', models.TextField(blank=True)),
                ('evaluator_notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildAssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('answer', models.JSONField(blank=True, default=dict)),
                ('is_correct', models.BooleanField(blank=True, db_index=True, null=True)),
                ('score_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_taken', models.PositiveIntegerField(blank=True, help_text='Time taken in seconds.', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['assessment', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(blank=True, max_length=120)),
                ('is_correct', models.BooleanField(db_index=True, default=False)),
                ('score_value', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['question', 'sort_order', 'id'],
            },
        ),
    ]
