# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('schools', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assessments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='schools.school'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='curriculum.skill'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['category', 'difficulty'], name='assessments_categor_71ba55_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['question_type', 'is_active'], name='assessments_questio_1b689f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['sort_order'], name='assessments_sort_or_370b5a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['is_deleted', 'created_at'], name='assessments_is_dele_820e0d_idx'),
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='childassessmentresponse',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_responses', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='childassessmentresponse',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_responses', to='users.childprofile'),
        ),
        migrations.AddField(
            model_name='childassessmentresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='child_responses', to='assessments.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_options', to='assessments.assessmentquestion'),
        ),
        migrations.AddField(
            model_name='childassessmentresponse',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_responses', to='assessments.questionoption'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['child', 'status'], name='assessments_child_i_0f0264_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'assessment_type'], name='assessments_school__81c31e_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['skill', 'status'], name='assessments_skill_i_1bda3c_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['survey_completed_at'], name='assessments_survey__956829_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['overall_score', 'reading_age'], name='assessments_overall_856c13_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['completed_at'], name='assessments_complet_74aa45_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_deleted', 'created_at'], name='assessments_is_dele_259d03_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['assessment'], name='assessments_assessm_cd82ea_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['reading_age'], name='assessments_reading_8ddcec_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['grade_equivalent'], name='assessments_grade_e_8873a3_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['is_deleted', 'created_at'], name='assessments_is_dele_d9674c_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'sort_order'], name='assessments_questio_ea24af_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['question', 'is_correct'], name='assessments_questio_e69d16_idx'),
        ),
        migrations.AddIndex(
            model_name='questionoption',
            index=models.Index(fields=['is_deleted', 'created_at'], name='assessments_is_dele_11698a_idx'),
        ),
        migrations.AddIndex(
            model_name='childassessmentresponse',
            index=models.Index(fields=['assessment', 'question'], name='assessments_assessm_7873df_idx'),
        ),
        migrations.AddIndex(
            model_name='childassessmentresponse',
            index=models.Index(fields=['child', 'question'], name='assessments_child_i_0fa7e9_idx'),
        ),
        migrations.AddIndex(
            model_name='childassessmentresponse',
            index=models.Index(fields=['question', 'is_correct'], name='assessments_questio_57e972_idx'),
        ),
        migrations.AddIndex(
            model_name='childassessmentresponse',
            index=models.Index(fields=['time_taken'], name='assessments_time_ta_be2ca7_idx'),
        ),
        migrations.AddIndex(
            model_name='childassessmentresponse',
            index=models.Index(fields=['is_deleted', 'created_at'], name='assessments_is_dele_d137b2_idx'),
        ),
    ]
