# Generated by Django 5.2.17 on 2026-10-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentaudioasset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-scheduled_for', '-created_at'], 'verbose_name': 'inventory', 'verbose_name_plural': 'inventories'},
        ),
        migrations.AlterModelOptions(
            name='assessmentaudioasset',
            options={'ordering': ['key'], 'verbose_name': 'inventory audio asset', 'verbose_name_plural': 'inventory audio assets'},
        ),
        migrations.AlterModelOptions(
            name='assessmentquestion',
            options={'ordering': ['category', 'difficulty', 'sort_order', 'id'], 'verbose_name': 'inventory question', 'verbose_name_plural': 'inventory questions'},
        ),
        migrations.AlterModelOptions(
            name='assessmentresult',
            options={'ordering': ['-created_at'], 'verbose_name': 'inventory result', 'verbose_name_plural': 'inventory results'},
        ),
        migrations.AlterModelOptions(
            name='childassessmentresponse',
            options={'ordering': ['assessment', 'created_at'], 'verbose_name': 'child inventory response', 'verbose_name_plural': 'child inventory responses'},
        ),
        migrations.AlterField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('screening', 'Screening'), ('diagnostic', 'Diagnostic'), ('formative', 'Formative'), ('summative', 'Summative')], db_index=True, max_length=32, verbose_name='inventory type'),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='assessments.assessment', verbose_name='inventory'),
        ),
        migrations.AlterField(
            model_name='childassessmentresponse',
            name='assessment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_responses', to='assessments.assessment', verbose_name='inventory'),
        ),
    ]
