# Generated by Django 5.1.15 on 2026-08-21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, help_text="Used in the public URL. Leave blank to generate it from the title.", max_length=220, unique=True)),
                ("excerpt", models.CharField(help_text="A short summary displayed on the blog landing page.", max_length=320)),
                ("body", models.TextField(help_text="Write in plain text. Paragraph breaks will be preserved on the public article.")),
                ("category", models.CharField(blank=True, max_length=80)),
                ("cover_image", models.ImageField(blank=True, upload_to="blog/covers/%Y/%m/")),
                ("cover_image_alt", models.CharField(blank=True, help_text="Required when a cover image is added so the article remains accessible.", max_length=240, verbose_name="cover image description")),
                ("status", models.CharField(choices=[("draft", "Draft"), ("published", "Published")], db_index=True, default="draft", max_length=16)),
                ("published_at", models.DateTimeField(blank=True, db_index=True, help_text="Set a future date to schedule publication.", null=True)),
                ("is_featured", models.BooleanField(db_index=True, default=False, help_text="Featured posts are promoted at the top of the blog landing page.")),
                ("seo_title", models.CharField(blank=True, help_text="Optional search and social title. The article title is used by default.", max_length=70)),
                ("seo_description", models.CharField(blank=True, help_text="Optional search description. The excerpt is used by default.", max_length=160)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="blog_posts", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-is_featured", "-published_at", "-created_at"],
                "indexes": [models.Index(fields=["status", "published_at"], name="blog_blogpo_status_aa5436_idx"), models.Index(fields=["is_featured", "published_at"], name="blog_blogpo_is_feat_ef56bf_idx")],
            },
        ),
    ]
