# Generated by Django 5.2.17 on 2026-09-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='body_format',
            field=models.CharField(choices=[('plain', 'Plain text'), ('html', 'Rich text')], default='plain', help_text='Rich text bodies are sanitised HTML written in the portal editor.', max_length=8),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='cover_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
