# Generated by Django 5.2.17 on 2026-10-03 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_inline_images'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_of', models.DateField(unique=True)),
                ('planned_at', models.DateTimeField()),
                ('pillar', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Preparing'), ('generating', 'Generating'), ('ready', 'Ready'), ('scheduled', 'Scheduled'), ('held', 'Needs review'), ('error', 'Generation failed'), ('skipped', 'Skipped')], default='pending', max_length=16)),
                ('context', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('auto_scheduled', models.BooleanField(default=False)),
                ('review_passed', models.BooleanField(default=False)),
                ('review_note', models.CharField(blank=True, max_length=500)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_week', to='blog.blogpost')),
            ],
            options={
                'ordering': ['planned_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogContentPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('paused', 'Paused'), ('review', 'Review first'), ('automatic', 'Automatic')], default='paused', max_length=16)),
                ('weekday', models.PositiveSmallIntegerField(default=2)),
                ('posting_hour', models.PositiveSmallIntegerField(default=9)),
                ('audience', models.CharField(choices=[('families', 'Families'), ('teachers', 'Teachers'), ('general', 'General')], default='families', max_length=16)),
                ('priorities', models.TextField(blank=True, max_length=2000)),
                ('promote_facebook', models.BooleanField(default=True)),
                ('promotion_delay_hours', models.PositiveSmallIntegerField(default=1)),
                ('preview_requested', models.BooleanField(default=False)),
                ('last_worker_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('pk', 1)), name='blog_single_content_plan'), models.CheckConstraint(condition=models.Q(('weekday__lte', 6)), name='blog_plan_weekday'), models.CheckConstraint(condition=models.Q(('posting_hour__gte', 8), ('posting_hour__lte', 20)), name='blog_plan_daytime'), models.CheckConstraint(condition=models.Q(('promotion_delay_hours__gte', 1), ('promotion_delay_hours__lte', 72)), name='blog_promotion_delay')],
            },
        ),
    ]
