from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from django.urls import include, path
from django.views.generic import RedirectView, TemplateView
from django.views.static import serve

from apps.assessments.views import assessment_audio, assessment_audio_status
from apps.crm.hiring_views import (HiringWorkspaceView, HiringUpdateView, HiringAssignView, HiringDocumentView, HiringAccessUpdateView, HiringFromContactView)
from apps.crm.views import (
    CrmCompanyDetailView,
    CrmCompanyCreateView,
    CrmCompanyListView,
    CrmCompanyUpdateView,
    CrmContactCreateView,
    CrmContactBulkAssignView,
    CrmContactDetailView,
    CrmContactDeleteView,
    CrmContactListView,
    CrmContactUpdateView,
    CrmDealCreateView,
    CrmDealDetailView,
    CrmDealRemoveView,
    CrmEnrollmentPersonEditView,
    CrmDealListView,
    CrmDealStageUpdateView,
    CrmDashboardView,
    CrmNoteCreateView,
    CrmTaskCompleteView,
    CrmTaskCreateView,
    CrmTeamView,
    CrmTriageListView,
    CrmTriageResolveView,
    FamilyResourcesView,
    NewsletterSignupView,
    NewsletterUnsubscribeView,
    SurveySubmissionView,
    WebsiteSignupView,
)
from apps.core.discovery_views import LlmsTxtView, RobotsTxtView, SitemapXmlView
from apps.sessions.views import RapidSessionLogView
from apps.users.onboarding_views import manage_users, resend_invitation, AcceptInvitationView, gmail_welcome
from apps.users.portal_views import (
    AssignLessonTemplateToChildView,
    AssignTeacherView,
    AssignTemplateToTeacherView,
    CreatePortalUserView,
    ConfirmPlacementRecommendationView,
    DemoLoginView,
    PortalDashboardView,
    PortalInboxView,
    PortalLoginView,
)

from apps.crm.calendar_views import CalendarSettingsView, GoogleCalendarConnectView, calendar_feed
from apps.crm.inventory_views import (
    InventoryListView, InventorySendView, InventoryDetailView, InventoryPublicView,
    InventorySlotsView, InventoryBookingView, InventoryPreviewView,
)

urlpatterns = [
    path("crm/calendar/google/connect/", GoogleCalendarConnectView.as_view(), name="crm_google_calendar_connect"),
    path("crm/calendar/", CalendarSettingsView.as_view(), name="crm_calendar_settings"),
    path("calendars/<uuid:token>.ics", calendar_feed, name="crm_calendar_feed"),
    path("portal/users/", manage_users, name="manage_users"),
    path("portal/users/invitations/<int:pk>/resend/", resend_invitation, name="resend_user_invitation"),
    path("account/setup/<uidb64>/<token>/", AcceptInvitationView.as_view(), name="user_invitation_accept"),
    path("portal/welcome/gmail/", gmail_welcome, name="gmail_welcome"),
    path("crm/", include("apps.crm_email.urls")),
    path("crm/assessments/", InventoryListView.as_view(), name="inventory_list"),
    path("crm/assessments/preview/", InventoryPreviewView.as_view(), name="inventory_preview"),
    path("crm/assessments/availability/", InventorySlotsView.as_view(), name="inventory_slots"),
    path("crm/contacts/<int:pk>/assessment/", InventorySendView.as_view(), name="inventory_send"),
    path("crm/assessments/<uuid:pk>/", InventoryDetailView.as_view(), name="inventory_detail"),
    path("reading-inventory/<str:token>/", InventoryPublicView.as_view(), name="inventory_public"),
    path("reading-inventory/<str:token>/book/", InventoryBookingView.as_view(), name="inventory_booking"),
    path("", TemplateView.as_view(template_name="index.html"), name="marketing_home"),
    path("robots.txt", RobotsTxtView.as_view(), name="robots_txt"),
    path("sitemap.xml", SitemapXmlView.as_view(), name="sitemap_xml"),
    path("llms.txt", LlmsTxtView.as_view(), name="llms_txt"),
    path("about/", TemplateView.as_view(template_name="about.html"), name="marketing_about"),
    path(
        "favicon.ico",
        serve,
        {
            "path": "logo/favicon.ico",
            "document_root": settings.BASE_DIR / "marketing-website" / "assets",
        },
        name="favicon",
    ),
    path("how-it-works/", TemplateView.as_view(template_name="how-it-works.html"), name="marketing_how_it_works"),
    path("families/", TemplateView.as_view(template_name="families.html"), name="marketing_families"),
    path("resources/", FamilyResourcesView.as_view(template_name="resources.html"), name="marketing_resources"),
    path("resources/", include("apps.resources.urls")),
    path("orlando/", TemplateView.as_view(template_name="orlando.html"), name="marketing_orlando"),
    path(
        "florida/",
        RedirectView.as_view(pattern_name="marketing_orlando", permanent=True),
        name="marketing_florida",
    ),
    path("faq/", TemplateView.as_view(template_name="faq.html"), name="marketing_faq"),
    path("foundation/", TemplateView.as_view(template_name="foundation.html"), name="marketing_foundation"),
    path("careers/", TemplateView.as_view(template_name="careers.html"), name="marketing_careers"),
    path("contact/", TemplateView.as_view(template_name="contact.html"), name="marketing_contact"),
    path("support/", TemplateView.as_view(template_name="support.html"), name="marketing_support"),
    path("privacy/", TemplateView.as_view(template_name="privacy.html"), name="marketing_privacy"),
    path(
        "approach/",
        RedirectView.as_view(pattern_name="marketing_how_it_works", permanent=True),
        name="marketing_approach",
    ),
    path("assessment/", TemplateView.as_view(template_name="assessment.html"), name="reading_assessment"),
    path("survey/", TemplateView.as_view(template_name="survey.html"), name="early_interest_survey"),
    path("blog/", include("apps.blog.urls")),
    path("login/", PortalLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(next_page="/"), name="logout"),
    path("dashboard/", PortalDashboardView.as_view(), name="portal_dashboard"),
    path("inbox/", PortalInboxView.as_view(), name="portal_inbox"),
    path("portal/sessions/rapid-log/", RapidSessionLogView.as_view(), name="rapid_session_log"),
    path("crm/hiring/", HiringWorkspaceView.as_view(), name="crm_hiring"),
    path("crm/hiring/<int:pk>/update/", HiringUpdateView.as_view(), name="crm_hiring_update"),
    path("crm/hiring/<int:pk>/assign/", HiringAssignView.as_view(), name="crm_hiring_assign"),
    path("crm/hiring/<int:pk>/documents/<str:kind>/", HiringDocumentView.as_view(), name="crm_hiring_document"),
    path("crm/team/<int:pk>/hiring-access/", HiringAccessUpdateView.as_view(), name="crm_hiring_access"),
    path("crm/contacts/<int:pk>/hiring/", HiringFromContactView.as_view(), name="crm_hiring_from_contact"),
    path("crm/", CrmDashboardView.as_view(), name="crm_dashboard"),
    path("crm/contacts/", CrmContactListView.as_view(), name="crm_contact_list"),
    path("crm/contacts/new/", CrmContactCreateView.as_view(), name="crm_contact_create"),
    path("crm/contacts/assign/", CrmContactBulkAssignView.as_view(), name="crm_contact_bulk_assign"),
    path("crm/team/", CrmTeamView.as_view(), name="crm_team"),
    path("crm/companies/", CrmCompanyListView.as_view(), name="crm_company_list"),
    path("crm/companies/new/", CrmCompanyCreateView.as_view(), name="crm_company_create"),
    path("crm/companies/<int:pk>/", CrmCompanyDetailView.as_view(), name="crm_company_detail"),
    path("crm/companies/<int:pk>/edit/", CrmCompanyUpdateView.as_view(), name="crm_company_update"),
    path("crm/deals/", CrmDealListView.as_view(), name="crm_deal_list"),
    path("crm/deals/new/", CrmDealCreateView.as_view(), name="crm_deal_new"),
    path("crm/deals/<int:pk>/person/", CrmEnrollmentPersonEditView.as_view(), name="crm_enrollment_person_edit"),
    path("crm/deals/<int:pk>/remove/", CrmDealRemoveView.as_view(), name="crm_deal_remove"),
    path("crm/deals/<int:pk>/", CrmDealDetailView.as_view(), name="crm_deal_detail"),
    path("crm/deals/<int:pk>/stage/", CrmDealStageUpdateView.as_view(), name="crm_deal_stage_update"),
    path("crm/triage/", CrmTriageListView.as_view(), name="crm_triage_list"),
    path("crm/triage/<int:pk>/resolve/", CrmTriageResolveView.as_view(), name="crm_triage_resolve"),
    path("crm/contacts/<int:pk>/delete/", CrmContactDeleteView.as_view(), name="crm_contact_delete"),
    path("crm/contacts/<int:pk>/", CrmContactDetailView.as_view(), name="crm_contact_detail"),
    path("crm/contacts/<int:pk>/update/", CrmContactUpdateView.as_view(), name="crm_contact_update"),
    path("crm/contacts/<int:pk>/deals/", CrmDealCreateView.as_view(), name="crm_deal_create"),
    path("crm/contacts/<int:pk>/notes/", CrmNoteCreateView.as_view(), name="crm_note_create"),
    path("crm/contacts/<int:pk>/tasks/", CrmTaskCreateView.as_view(), name="crm_task_create"),
    path(
        "crm/contacts/<int:pk>/tasks/<int:activity_id>/complete/",
        CrmTaskCompleteView.as_view(),
        name="crm_task_complete",
    ),
    path("crm/signup/", WebsiteSignupView.as_view(), name="crm_signup"),
    path("crm/survey/", SurveySubmissionView.as_view(), name="crm_survey_submit"),
    path("newsletter/subscribe/", NewsletterSignupView.as_view(), name="newsletter_signup"),
    path(
        "newsletter/unsubscribe/<str:token>/",
        NewsletterUnsubscribeView.as_view(),
        name="newsletter_unsubscribe",
    ),
    path("assign-teacher/", AssignTeacherView.as_view(), name="assign_teacher"),
    path("portal/templates/assign-teacher/", AssignTemplateToTeacherView.as_view(), name="portal_assign_template_to_teacher"),
    path("portal/lessons/assign-child/", AssignLessonTemplateToChildView.as_view(), name="portal_assign_lesson_to_child"),
    path("portal/users/create/", CreatePortalUserView.as_view(), name="portal_create_user"),
    path(
        "portal/placements/confirm/",
        ConfirmPlacementRecommendationView.as_view(),
        name="portal_confirm_placement",
    ),
    path("demo-login/<str:role>/", DemoLoginView.as_view(), name="demo_login"),
    path("assessment-audio/status/", assessment_audio_status, name="assessment_audio_status"),
    path("assessment-audio/<str:key>.mp3", assessment_audio, name="assessment_audio"),
    path("assets/<path:path>", serve, {"document_root": settings.BASE_DIR / "marketing-website" / "assets"}, name="marketing_assets"),
    path("admin/", admin.site.urls),
    path("api/", include("apps.api.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
