# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('guardian', 'Guardian'), ('student', 'Student')], db_index=True, default='guardian', max_length=32)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'email'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=120)),
                ('entity_type', models.CharField(db_index=True, max_length=120)),
                ('entity_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('grade_level', models.CharField(blank=True, choices=[('pre_k', 'Pre-K'), ('kindergarten', 'Kindergarten'), ('grade_1', 'Grade 1'), ('grade_2', 'Grade 2'), ('grade_3', 'Grade 3'), ('grade_4', 'Grade 4'), ('grade_5', 'Grade 5'), ('other', 'Other')], max_length=32)),
                ('student_identifier', models.CharField(blank=True, max_length=120)),
                ('learning_profile', models.JSONField(blank=True, default=dict)),
                ('accommodations', models.JSONField(blank=True, default=list)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='schools.school')),
                ('user', models.OneToOneField(blank=True, limit_choices_to={'role': 'student'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='GuardianRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relationship_type', models.CharField(choices=[('parent', 'Parent'), ('legal_guardian', 'Legal Guardian'), ('caregiver', 'Caregiver'), ('other', 'Other')], max_length=32)),
                ('is_primary', models.BooleanField(default=False)),
                ('consent_status', models.CharField(choices=[('pending', 'Pending'), ('granted', 'Granted'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('consent_expires_at', models.DateTimeField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to='users.childprofile')),
                ('guardian', models.ForeignKey(limit_choices_to={'role': 'guardian'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardian_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['child__last_name', 'child__first_name', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('data_processing', 'Data Processing'), ('school_sharing', 'School Sharing'), ('assessment', 'Assessment')], max_length=32)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('revoked', 'Revoked'), ('expired', 'Expired')], db_index=True, max_length=20)),
                ('version', models.CharField(blank=True, max_length=64)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to='users.childprofile')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_logs', to=settings.AUTH_USER_MODEL)),
                ('guardian_relationship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='users.guardianrelationship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=255)),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/avatars/')),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('onboarding_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__email'],
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='users_custo_email_c80f75_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['role', 'is_active'], name='users_custo_role_e4c2f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_deleted', 'created_at'], name='users_custo_is_dele_401197_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['actor', 'created_at'], name='users_audit_actor_i_d823e9_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='users_audit_entity__318d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='users_audit_action_9b343e_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['school', 'grade_level'], name='users_child_school__356c0c_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['student_identifier'], name='users_child_student_6b2114_idx'),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['is_deleted', 'created_at'], name='users_child_is_dele_24ec23_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['guardian', 'child'], name='users_guard_guardia_b4c5c1_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['child', 'is_primary'], name='users_guard_child_i_bd35da_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['consent_status', 'consent_expires_at'], name='users_guard_consent_46ebf5_idx'),
        ),
        migrations.AddIndex(
            model_name='guardianrelationship',
            index=models.Index(fields=['is_deleted', 'created_at'], name='users_guard_is_dele_112cac_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardianrelationship',
            constraint=models.UniqueConstraint(fields=('guardian', 'child'), name='unique_guardian_child_relationship'),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['guardian', 'consent_type', 'status'], name='users_conse_guardia_ab7548_idx'),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['child', 'consent_type', 'status'], name='users_conse_child_i_41ee10_idx'),
        ),
        migrations.AddIndex(
            model_name='consentlog',
            index=models.Index(fields=['guardian_relationship', 'created_at'], name='users_conse_guardia_ffe548_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user', 'is_deleted'], name='users_profi_user_id_85f54d_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['created_at'], name='users_profi_created_f60c54_idx'),
        ),
    ]
