# Generated by Django 5.1.15 on 2026-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='availability_windows',
            field=models.JSONField(blank=True, default=list, help_text='Guardian-provided weekly availability windows for future scheduling.'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='idea_parent_consent_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('revoked', 'Revoked')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='idea_parent_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='iep_status',
            field=models.CharField(choices=[('not_reported', 'Not reported'), ('no_iep', 'No IEP'), ('active', 'Active IEP'), ('in_review', 'IEP in review')], db_index=True, default='not_reported', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='iep_team_approval_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('revoked', 'Revoked')], db_index=True, default='not_required', max_length=20),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='iep_team_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='childprofile',
            index=models.Index(fields=['iep_status', 'idea_parent_consent_status', 'iep_team_approval_status'], name='users_child_iep_sta_781164_idx'),
        ),
    ]
