# Generated by Django 5.1.15 on 2026-07-24 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


BACKFILL_SOURCE = "legacy-child-profile-backfill"


def backfill_idea_consent_records(apps, schema_editor):
    ChildProfile = apps.get_model("users", "ChildProfile")
    ConsentRecord = apps.get_model("users", "ConsentRecord")
    records = []
    candidates = ChildProfile.objects.filter(school_id__isnull=False).exclude(
        idea_parent_consent_status="not_required",
        iep_team_approval_status="not_required",
        idea_parent_consented_at__isnull=True,
        iep_team_approved_at__isnull=True,
    )
    for child in candidates.iterator():
        parent_granted = (
            child.idea_parent_consent_status == "approved"
            and child.idea_parent_consented_at is not None
        )
        team_granted = (
            child.iep_team_approval_status == "approved"
            and child.iep_team_approved_at is not None
        )
        if parent_granted and team_granted:
            status = "granted"
            granted_at = max(child.idea_parent_consented_at, child.iep_team_approved_at)
        elif "revoked" in {child.idea_parent_consent_status, child.iep_team_approval_status}:
            status = "revoked"
            granted_at = None
        elif "declined" in {child.idea_parent_consent_status, child.iep_team_approval_status}:
            status = "denied"
            granted_at = None
        else:
            status = "pending"
            granted_at = None
        records.append(
            ConsentRecord(
                child_id=child.id,
                center_id=child.school_id,
                consent_type="idea_iep",
                status=status,
                version=1,
                granted_at=granted_at,
                evidence_notes="Backfilled from legacy ChildProfile IDEA authorization fields.",
                source_document_ref=BACKFILL_SOURCE,
            )
        )
    ConsentRecord.objects.bulk_create(records, ignore_conflicts=True)


def remove_backfilled_idea_consent_records(apps, schema_editor):
    ConsentRecord = apps.get_model("users", "ConsentRecord")
    ConsentRecord.objects.filter(source_document_ref=BACKFILL_SOURCE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('consent_type', models.CharField(choices=[('general', 'General'), ('idea_iep', 'IDEA / IEP'), ('data_use', 'Data Use'), ('other', 'Other')], db_index=True, max_length=24)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('denied', 'Denied'), ('revoked', 'Revoked'), ('pending', 'Pending')], db_index=True, max_length=16)),
                ('version', models.PositiveIntegerField(editable=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_notes', models.TextField(blank=True)),
                ('source_document_ref', models.CharField(blank=True, max_length=255)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consent_records', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records_created', to=settings.AUTH_USER_MODEL)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records_granted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-version'],
                'indexes': [models.Index(fields=['center', 'consent_type', 'status'], name='users_conse_center__476739_idx'), models.Index(fields=['child', 'consent_type', '-version'], name='users_conse_child_i_a7f8e8_idx'), models.Index(fields=['expires_at', 'status'], name='users_conse_expires_b5e0fe_idx'), models.Index(fields=['is_deleted', 'created_at'], name='users_conse_is_dele_e9a02e_idx')],
                'constraints': [models.UniqueConstraint(fields=('child', 'consent_type', 'version'), name='unique_child_consent_type_version')],
            },
        ),
        migrations.RunPython(
            backfill_idea_consent_records,
            remove_backfilled_idea_consent_records,
        ),
    ]
