# Generated by Django 5.1.15 on 2026-07-24 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_consentrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.UUIDField()),
                ('push_token', models.CharField(blank=True, max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('app_version', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='users_mobil_user_id_2e0ef4_idx'), models.Index(fields=['push_token', 'environment'], name='users_mobil_push_to_ffd5cb_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id'), name='unique_user_mobile_device')],
            },
        ),
    ]
