# Generated by Django 5.1.15 on 2026-09-04 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_mobiledevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('crm_user', 'CRM User'), ('school_admin', 'School Admin'), ('teacher', 'Teacher'), ('guardian', 'Guardian'), ('student', 'Student')], db_index=True, default='guardian', max_length=32),
        ),
    ]
