# Generated by Django 5.1.15 on 2026-09-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="hiring_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Access private teacher hiring records in the CRM.",
            ),
        ),
    ]
