# Generated by Django 5.2.17 on 2026-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_contact_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentlog',
            name='consent_type',
            field=models.CharField(choices=[('terms', 'Terms'), ('privacy', 'Privacy'), ('data_processing', 'Data Processing'), ('school_sharing', 'School Sharing'), ('assessment', 'Inventory')], max_length=32),
        ),
    ]
