# Generated by Django 5.1.15 on 2026-05-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="audience",
            field=models.CharField(
                choices=[
                    ("parent", "Parent"),
                    ("teacher", "Teacher"),
                    ("school", "School or District"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="parent",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="linked_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crm_leads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="organization_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["audience", "status"], name="crm_lead_audienc_1b3e6e_idx"),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["linked_user", "status"], name="crm_lead_linked__b92b8e_idx"),
        ),
    ]
