# Generated by Django 5.1.15 on 2026-08-28 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


STAGE_MAP = {
    'family_enrollment': {
        'new': 'family_lead_nurture',
        'consultation': 'family_consultation',
        'qualified': 'family_assessment',
        'enrollment_offered': 'family_enrolled',
        'enrolled': 'family_enrolled',
        'lost': 'family_lost',
    },
    'referral_partners': {
        'identified': 'partner_identified',
        'contacted': 'partner_contacted',
        'qualified': 'partner_meeting',
        'active_partner': 'partner_active',
        'inactive': 'partner_dormant',
        'lost': 'partner_dormant',
    },
    'foundation_donors': {
        'identified': 'donor_identified',
        'cultivating': 'donor_cultivation',
        'ask_planned': 'donor_ask',
        'ask_made': 'donor_ask',
        'pledged': 'donor_committed',
        'gift_received': 'donor_committed',
        'stewardship': 'donor_stewardship',
        'lost': 'donor_declined',
    },
    'foundation_grants': {
        'qualified': 'grant_need_intro',
        'loi': 'grant_invited',
        'application': 'grant_invited',
        'submitted': 'grant_submitted',
        'due_diligence': 'grant_relationship',
        'awarded': 'grant_awarded',
        'reporting_renewal': 'grant_awarded',
        'declined': 'grant_declined',
    },
    'equity_investment': {
        'identified': 'equity_need_intro',
        'contacted': 'equity_introduced',
        'qualified': 'equity_first_meeting',
        'due_diligence': 'equity_diligence',
        'terms': 'equity_term_sheet',
        'committed': 'equity_closed_won',
        'funded': 'equity_closed_won',
        'passed': 'equity_passed',
    },
}


def align_existing_deals(apps, schema_editor):
    Opportunity = apps.get_model('crm', 'Opportunity')
    for deal in Opportunity.objects.all().iterator():
        legacy_stage = deal.stage
        deal.stage = STAGE_MAP.get(deal.pipeline, {}).get(
            legacy_stage,
            STAGE_MAP.get(deal.pipeline, {}).get('identified', 'family_lead_nurture'),
        )
        metadata = dict(deal.metadata or {})
        metadata.update({
            'needs_naming_review': True,
            'master_pipeline_v2_legacy_stage': legacy_stage,
        })
        deal.metadata = metadata
        if deal.pipeline == 'foundation_grants':
            deal.capital_lane = 'foundation'
        deal.save(update_fields=['stage', 'metadata', 'capital_lane'])


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_company_pipelines_and_triage'),
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='bucket',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='campaign_year',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='capital_lane',
            field=models.CharField(blank=True, choices=[('company', 'ClearCode, Inc.'), ('foundation', 'Foundation'), ('both', 'Both')], max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='cycle_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='donor_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('daf', 'Donor-advised fund'), ('family_foundation', 'Family foundation')], max_length=32),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='esa_program',
            field=models.CharField(blank=True, choices=[('fes_ua', 'FES-UA'), ('fes_eo', 'FES-EO'), ('pep', 'PEP'), ('ftc', 'FTC')], max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='funding_type',
            field=models.CharField(blank=True, choices=[('esa', 'ESA'), ('private_pay', 'Private-pay')], max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='gift_level',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='grade_band',
            field=models.CharField(blank=True, choices=[('prek_2', 'PreK-2'), ('3_5', '3-5'), ('6_8', '6-8'), ('multi_child', 'Multi-child')], max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='grant_cycle_application_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='in_catchment_zip',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='investment_round',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='partner_type',
            field=models.CharField(blank=True, choices=[('pediatric', 'Pediatric practice'), ('therapy', 'Therapy clinic'), ('private_school', 'Private school'), ('homeschool', 'Homeschool co-op / microschool')], max_length=32),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='priority',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], db_index=True, max_length=16),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='program_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='referral_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_enrollment_deals', to='crm.company'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='referral_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='student_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='segment_tags',
            field=models.CharField(blank=True, help_text='Comma-separated segment properties; never used as pipeline names.', max_length=255),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='term_year',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='pipeline',
            field=models.CharField(choices=[('family_enrollment', 'Families / Enrollment'), ('referral_partners', 'School & Teacher Referral Partners'), ('foundation_donors', 'Foundation Donors'), ('foundation_grants', 'Foundation Grants / PRIs'), ('equity_investment', 'Equity / Investment')], db_index=True, default='family_enrollment', max_length=32),
        ),
        migrations.AddField(
            model_name='intaketriage',
            name='advocate_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(align_existing_deals, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('family_lead_nurture', 'Lead / Nurture'), ('family_waitlist', 'Waitlist'), ('family_consultation', 'Consultation Scheduled'), ('family_assessment', 'Assessment'), ('family_enrolled', 'Enrolled'), ('family_active', 'Active'), ('family_lost', 'Lost'), ('family_churned', 'Churned'), ('partner_identified', 'Identified'), ('partner_contacted', 'Contacted'), ('partner_meeting', 'Meeting / Lunch-and-Learn'), ('partner_active', 'Active Referrer'), ('partner_dormant', 'Dormant'), ('donor_identified', 'Identified'), ('donor_cultivation', 'Cultivation'), ('donor_ask', 'Ask'), ('donor_committed', 'Committed / Gift'), ('donor_stewardship', 'Stewardship'), ('donor_declined', 'Declined'), ('grant_need_intro', 'Need Intro'), ('grant_relationship', 'Relationship Building'), ('grant_invited', 'LOI / Application Invited'), ('grant_submitted', 'Application Submitted'), ('grant_awarded', 'Awarded'), ('grant_declined', 'Declined'), ('equity_need_intro', 'Need Intro'), ('equity_introduced', 'Introduced'), ('equity_first_meeting', 'First Meeting'), ('equity_diligence', 'Diligence / Data Room'), ('equity_term_sheet', 'Term Sheet'), ('equity_closed_won', 'Closed-Won'), ('equity_passed', 'Passed')], db_index=True, default='family_lead_nurture', max_length=32),
        ),
        migrations.AddIndex(
            model_name='opportunity',
            index=models.Index(fields=['pipeline', 'priority'], name='crm_deal_pipeline_priority'),
        ),
    ]
