# Generated by Django 5.1.15 on 2026-09-14 14:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_recruitinginterest_candidate_pool_and_owner"),
        ("crm", "0008_alter_formsubmission_form_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HiringCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("application", "Application received"),
                            ("screening", "Initial screening"),
                            ("interview", "Interview / teaching demonstration"),
                            ("decision", "Hiring decision"),
                            ("offer", "Offer sent"),
                            ("onboarding", "Onboarding"),
                            ("ready", "Ready for assignment"),
                            ("hold", "On hold"),
                            ("not_selected", "Not selected"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        db_index=True,
                        default="application",
                        max_length=24,
                    ),
                ),
                (
                    "stage_entered_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "next_action",
                    models.CharField(default="Review application", max_length=255),
                ),
                ("due_date", models.DateField(blank=True, db_index=True, null=True)),
                ("blocker", models.TextField(blank=True)),
                ("outcome_reason", models.TextField(blank=True)),
                ("review_date", models.DateField(blank=True, null=True)),
                ("checklist", models.JSONField(blank=True, default=list)),
                ("evaluation_notes", models.TextField(blank=True)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("pending", "Not yet decided"),
                            ("hire", "Proceed with hire"),
                            ("decline", "Do not proceed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("decision_notes", models.TextField(blank=True)),
                ("offer_sent_on", models.DateField(blank=True, null=True)),
                ("offer_terms", models.TextField(blank=True)),
                (
                    "offer_response",
                    models.CharField(
                        choices=[
                            ("pending", "Awaiting response"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("offer_responded_on", models.DateField(blank=True, null=True)),
                ("onboarding_notes", models.TextField(blank=True)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "application",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hiring",
                        to="core.recruitinginterest",
                    ),
                ),
                (
                    "lead",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hiring",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "created_at", "pk"],
            },
        ),
        migrations.CreateModel(
            name="HiringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("summary", models.CharField(max_length=500)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="crm.hiringcandidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="hiringcandidate",
            index=models.Index(
                fields=["stage", "due_date"], name="crm_hiring_stage_due"
            ),
        ),
    ]
