# Generated by Django 5.2.17 on 2026-09-14 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_parent_inventory"),
        ("crm_email", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymail",
            name="provider_message",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_delivery",
                to="crm_email.message",
            ),
        ),
        migrations.AlterField(
            model_name="inventorymail",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued for Google delivery"),
                    ("sending", "Sending / delivery uncertain"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
