# Generated by Django 5.2.17 on 2026-09-14 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0012_inventorymail_provider_message_and_more"),
        ("crm_email", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                (
                    "customer_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_customer_receipt",
                        to="crm_email.message",
                    ),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="crm.formsubmission",
                    ),
                ),
                (
                    "team_message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="website_team_receipt",
                        to="crm_email.message",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
