# Generated by Django 5.2.17 on 2026-09-14 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_hostcalendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hostcalendar',
            name='encrypted_google_refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hostcalendar',
            name='google_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.CreateModel(
            name='CalendarAuthorization',
            fields=[
                ('state_hash', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_hash', models.CharField(max_length=64)),
                ('encrypted_verifier', models.TextField()),
                ('nonce', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
