# Generated by Django 5.2.17 on 2026-09-14 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0015_hostcalendar_encrypted_google_refresh_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostcalendar",
            name="blocking_timezone",
            field=models.CharField(default="America/New_York", max_length=64),
        ),
        migrations.CreateModel(
            name="CalendarDateOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("none", "No block"),
                            ("range", "Block a time range"),
                            ("all", "Block all day"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                ("starts_at", models.TimeField(blank=True, null=True)),
                ("ends_at", models.TimeField(blank=True, null=True)),
                ("date", models.DateField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="date_overrides",
                        to="crm.hostcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ends_at__isnull", False),
                                ("mode", "range"),
                                ("starts_at__isnull", False),
                                models.Q(
                                    ("starts_at", models.F("ends_at")), _negated=True
                                ),
                            ),
                            models.Q(
                                ("ends_at__isnull", True),
                                ("mode__in", ["none", "all"]),
                                ("starts_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="calendardateoverride_valid_range",
                    ),
                    models.UniqueConstraint(
                        fields=("calendar", "date"), name="unique_host_date_override"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="WeeklyCalendarBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("none", "No block"),
                            ("range", "Block a time range"),
                            ("all", "Block all day"),
                        ],
                        default="none",
                        max_length=5,
                    ),
                ),
                ("starts_at", models.TimeField(blank=True, null=True)),
                ("ends_at", models.TimeField(blank=True, null=True)),
                ("weekday", models.PositiveSmallIntegerField()),
                (
                    "calendar",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_blocks",
                        to="crm.hostcalendar",
                    ),
                ),
            ],
            options={
                "ordering": ["weekday"],
                "abstract": False,
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("ends_at__isnull", False),
                                ("mode", "range"),
                                ("starts_at__isnull", False),
                                models.Q(
                                    ("starts_at", models.F("ends_at")), _negated=True
                                ),
                            ),
                            models.Q(
                                ("ends_at__isnull", True),
                                ("mode__in", ["none", "all"]),
                                ("starts_at__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="weeklycalendarblock_valid_range",
                    ),
                    models.UniqueConstraint(
                        fields=("calendar", "weekday"), name="unique_host_weekday_block"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__lte", 6)),
                        name="valid_block_weekday",
                    ),
                ],
            },
        ),
    ]
