# Generated by Django 5.2.17 on 2026-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_lead_pipeline_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='investment_category',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
