# Generated by Django 5.2.17 on 2026-09-24 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_opportunity_investment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=32)),
                ('timezone', models.CharField(max_length=64)),
                ('child_age_grade', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_bookings', to='crm.lead')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_booking', to='crm.consultationslot')),
                ('submission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_booking', to='crm.formsubmission')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
