# Generated by Django 5.2.17 on 2026-09-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0021_consultation_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorymail",
            name="body_html",
            field=models.TextField(blank=True),
        ),
    ]
