# Generated by Django 5.2.17 on 2026-09-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0022_inventorymail_body_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="newslettercampaign",
            name="body_html",
            field=models.TextField(
                blank=True,
                help_text="Rich version of the body from the CRM newsletter editor; used for the HTML email when set.",
            ),
        ),
    ]
