# ruff: noqa: RUF012
# Generated by Django 5.2.17 on 2026-09-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0025_newslettersubscription_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calendardateoverride",
            name="mode",
            field=models.CharField(
                choices=[
                    ("none", "Open to bookings"),
                    ("range", "Block these hours"),
                    ("all", "Block the whole day"),
                ],
                default="none",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="weeklycalendarblock",
            name="mode",
            field=models.CharField(
                choices=[
                    ("none", "Open to bookings"),
                    ("range", "Block these hours"),
                    ("all", "Block the whole day"),
                ],
                default="none",
                max_length=5,
            ),
        ),
    ]
