# Generated by Django 5.2.17 on 2026-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_alter_calendardateoverride_mode_and_more'),
        ('crm', '0026_calendar_block_mode_labels'),
    ]

    operations = [
    ]
