# Generated by Django 5.2.17 on 2026-09-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_published_hours(apps, schema_editor):
    from apps.crm.open_hours import ensure_published_hours

    ensure_published_hours()


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0027_merge_calendar_mode_migrations"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsultationOpenWindow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("starts_at", models.TimeField()),
                ("ends_at", models.TimeField()),
                (
                    "timezone",
                    models.CharField(default="America/New_York", max_length=64),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_open_windows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["date", "starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "date", "starts_at"),
                        name="unique_host_open_window_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="consultation_open_window_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsultationHoursSeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_hours_seeds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(seed_published_hours, migrations.RunPython.noop),
    ]
