# Generated by Django 5.2.17 on 2026-10-02 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_consultation_open_windows'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsubmission',
            name='form_type',
            field=models.CharField(choices=[('consultation', 'Consultation request'), ('assessment', 'Inventory follow-up'), ('survey', 'Early interest survey'), ('career', 'Career interest'), ('newsletter', 'Newsletter signup'), ('website', 'Website inquiry'), ('family_resources', 'Free resources modal')], db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='stage',
            field=models.CharField(choices=[('family_lead_nurture', 'Lead / Nurture'), ('family_waitlist', 'Waitlist'), ('family_consultation', 'Consultation Scheduled'), ('family_assessment', 'Inventory'), ('family_enrolled', 'Enrolled'), ('family_active', 'Active'), ('family_lost', 'Lost'), ('family_churned', 'Churned'), ('partner_identified', 'Identified'), ('partner_contacted', 'Contacted'), ('partner_meeting', 'Meeting / Lunch-and-Learn'), ('partner_active', 'Active Referrer'), ('partner_dormant', 'Dormant'), ('donor_identified', 'Identified'), ('donor_cultivation', 'Cultivation'), ('donor_ask', 'Ask'), ('donor_committed', 'Committed / Gift'), ('donor_stewardship', 'Stewardship'), ('donor_declined', 'Declined'), ('grant_need_intro', 'Need Intro'), ('grant_relationship', 'Relationship Building'), ('grant_invited', 'LOI / Application Invited'), ('grant_submitted', 'Application Submitted'), ('grant_awarded', 'Awarded'), ('grant_declined', 'Declined'), ('equity_need_intro', 'Need Intro'), ('equity_introduced', 'Introduced'), ('equity_first_meeting', 'First Meeting'), ('equity_diligence', 'Diligence / Data Room'), ('equity_term_sheet', 'Term Sheet'), ('equity_closed_won', 'Closed-Won'), ('equity_passed', 'Passed')], db_index=True, default='family_lead_nurture', max_length=32),
        ),
    ]
