# Generated by Django 5.2.17 on 2026-10-02 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_inventory_display_wording'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.CharField(choices=[('unrated', 'Unrated'), ('cold', 'COLD'), ('warm', 'WARM'), ('hot', 'HOT')], db_index=True, default='unrated', help_text='Hot: ready for prompt follow-up. Warm: interested and considering. Cold: little engagement. Unrated: not assessed yet.', max_length=16, verbose_name='Priority status'),
        ),
    ]
