# Generated by Django 5.1.15 on 2026-07-24 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_placementrecommendation_final_curriculum'),
        ('scheduling', '0001_initial'),
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulebooking',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedulebooking',
            name='sync_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedulebooking',
            name='sync_error',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ScheduleGroupProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField()),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='proposed', max_length=20)),
                ('rationale', models.TextField(blank=True)),
                ('signature', models.CharField(max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_group_proposals', to='schools.school')),
                ('children', models.ManyToManyField(related_name='schedule_group_proposals', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_schedule_group_proposals', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_group_proposals', to='curriculum.curriculum')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_schedule_group_proposals', to=settings.AUTH_USER_MODEL)),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_group_proposals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-score', 'starts_at', 'specialist_id'],
            },
        ),
        migrations.AddField(
            model_name='schedulebooking',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='scheduling.schedulegroupproposal'),
        ),
        migrations.AddIndex(
            model_name='schedulegroupproposal',
            index=models.Index(fields=['center', 'status', 'starts_at'], name='scheduling__center__41ac6f_idx'),
        ),
        migrations.AddIndex(
            model_name='schedulegroupproposal',
            index=models.Index(fields=['specialist', 'starts_at'], name='scheduling__special_203d4b_idx'),
        ),
        migrations.AddConstraint(
            model_name='schedulegroupproposal',
            constraint=models.UniqueConstraint(fields=('center', 'signature'), name='unique_center_schedule_proposal_signature'),
        ),
    ]
