# Generated by Django 5.1.15 on 2026-07-24 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0007_sequenceplan_sequenceplanitem_skillcrosswalk_and_more'),
        ('scheduling', '0002_schedulebooking_last_sync_at_and_more'),
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('skill_band', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notes', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructional_groups', to='schools.school')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructional_groups', to='curriculum.curriculum')),
                ('primary_specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_instructional_groups', to=settings.AUTH_USER_MODEL)),
                ('sequence_end', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_ending_here', to='curriculum.curriculumsequence')),
                ('sequence_start', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups_starting_here', to='curriculum.curriculumsequence')),
            ],
            options={
                'ordering': ['center__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructional_group_memberships', to='users.childprofile')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scheduling.group')),
            ],
            options={
                'ordering': ['group', 'child__last_name', 'child__first_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='instructional_groups', through='scheduling.GroupMembership', to='users.childprofile'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'child'], name='scheduling__group_i_0df58a_idx'),
        ),
        migrations.AddConstraint(
            model_name='groupmembership',
            constraint=models.UniqueConstraint(fields=('group', 'child'), name='unique_instructional_group_child'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['center', 'curriculum', 'is_active'], name='scheduling__center__fe5066_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['primary_specialist', 'is_active'], name='scheduling__primary_9ff016_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['sequence_start', 'sequence_end'], name='scheduling__sequenc_5aff8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('center', 'name'), name='unique_active_group_name_per_center'),
        ),
    ]
