# Generated by Django 5.1.15 on 2026-05-17 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmembership',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_membership_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='schools.school'),
        ),
        migrations.AddField(
            model_name='schoolmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['school', 'role'], name='schools_sch_school__926499_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['user', 'role'], name='schools_sch_user_id_ce486a_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolmembership',
            index=models.Index(fields=['is_deleted', 'created_at'], name='schools_sch_is_dele_079c6d_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolmembership',
            constraint=models.UniqueConstraint(fields=('school', 'user'), name='unique_school_membership'),
        ),
    ]
