# Generated by Django 5.1.15 on 2026-07-24 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculum', '0004_curriculum_curriculumsequence_studentplacement_and_more'),
        ('schools', '0002_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], db_index=True, default='scheduled', max_length=20)),
                ('intervention_part', models.CharField(choices=[('pfr_1a', 'PFR Session 1a'), ('pfr_1b', 'PFR Session 1b'), ('og_concept', 'OG+ Concept Session')], db_index=True, max_length=20)),
                ('scheduled_start', models.DateTimeField(db_index=True)),
                ('started_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('activities_completed', models.JSONField(blank=True, default=list)),
                ('item_sets', models.JSONField(blank=True, default=dict)),
                ('accuracy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('time_to_mastery_signals', models.JSONField(blank=True, default=dict)),
                ('error_patterns', models.JSONField(blank=True, default=list)),
                ('behavioral_observations', models.JSONField(blank=True, default=list)),
                ('next_session_direction', models.TextField(blank=True)),
                ('home_practice_suggestion', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervention_sessions', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='curriculum.curriculumsequence')),
                ('specialist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='specialist_sessions', to=settings.AUTH_USER_MODEL)),
                ('targeted_positions', models.ManyToManyField(blank=True, related_name='targeted_in_sessions', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('snapshot', models.JSONField(default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intervention_session_revisions', to='schools.school')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervention_session_revisions', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='intervention_sessions.session')),
            ],
            options={
                'ordering': ['session', '-revision'],
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['center', 'scheduled_start'], name='interventio_center__1a3023_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['child', 'scheduled_start'], name='interventio_child_i_e2d940_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['specialist', 'scheduled_start'], name='interventio_special_a5aa26_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['curriculum_position', 'status'], name='interventio_curricu_36392c_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['intervention_part', 'status'], name='interventio_interve_6fd502_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['is_deleted', 'created_at'], name='interventio_is_dele_fc2fa4_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrevision',
            index=models.Index(fields=['center', 'created_at'], name='interventio_center__9b4520_idx'),
        ),
        migrations.AddIndex(
            model_name='sessionrevision',
            index=models.Index(fields=['session', 'revision'], name='interventio_session_dccc97_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessionrevision',
            constraint=models.UniqueConstraint(fields=('session', 'revision'), name='unique_intervention_session_revision'),
        ),
    ]
