# Generated by Django 5.1.15 on 2026-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='accuracy_denominator',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='accuracy_numerator',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
