# Generated by Django 5.1.15 on 2026-07-24 17:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


COMMON_CAPTURE_PROPERTIES = {
    'activities_completed': {'type': 'array', 'default': []},
    'item_sets': {'type': 'object', 'default': {}},
    'time_to_mastery_signals': {'type': 'object', 'default': {}},
    'error_patterns': {'type': 'array', 'default': []},
    'behavioral_observations': {'type': 'array', 'default': []},
}
COMMON_REQUIRED_FIELDS = [
    'activities_completed',
    'item_sets',
    'time_to_mastery_signals',
    'next_session_direction',
    'home_practice_suggestion',
]


def _capture_schema(item_set_keys, activity_codes):
    properties = {key: dict(value) for key, value in COMMON_CAPTURE_PROPERTIES.items()}
    properties['item_sets']['sections'] = item_set_keys
    return {
        'required': COMMON_REQUIRED_FIELDS,
        'properties': properties,
        'activity_codes': activity_codes,
    }


SEEDED_TEMPLATES = {
    ('PFR-A-01', 'pfr_1a'): {
        'title': 'PFR Level A Lesson 1 - Session 1a',
        'item_set_keys': ['sound_drill', 'word_reading', 'word_spelling'],
        'activity_codes': ['phonemic_awareness', 'sound_drill', 'word_reading', 'word_spelling'],
    },
    ('PFR-A-01', 'pfr_1b'): {
        'title': 'PFR Level A Lesson 1 - Session 1b',
        'item_set_keys': ['review', 'high_frequency_words', 'connected_text'],
        'activity_codes': ['review', 'high_frequency_words', 'connected_text'],
    },
    ('OG-001', 'og_concept'): {
        'title': 'OG+ Concept 1 - Phoneme awareness',
        'item_set_keys': ['review_items', 'new_concept_items', 'encoding_items'],
        'activity_codes': [
            'phonological_awareness',
            'three_part_drill',
            'concept_instruction',
            'word_reading',
            'encoding',
            'connected_text',
        ],
    },
}


def seed_templates_and_observations(apps, schema_editor):
    CurriculumSequence = apps.get_model('curriculum', 'CurriculumSequence')
    Session = apps.get_model('intervention_sessions', 'Session')
    SessionTemplate = apps.get_model('intervention_sessions', 'SessionTemplate')
    SkillObservation = apps.get_model('intervention_sessions', 'SkillObservation')

    templates = {}
    for position in CurriculumSequence.objects.filter(code__in={key[0] for key in SEEDED_TEMPLATES}):
        for (position_code, session_part), definition in SEEDED_TEMPLATES.items():
            if position.code != position_code:
                continue
            template, _ = SessionTemplate.objects.update_or_create(
                center_id=position.center_id,
                curriculum_id=position.curriculum_id,
                curriculum_position_id=position.id,
                session_part=session_part,
                version=1,
                defaults={
                    'title': definition['title'],
                    'capture_fields': _capture_schema(
                        definition['item_set_keys'],
                        definition['activity_codes'],
                    ),
                    'is_active': True,
                    'metadata': {
                        'seed_key': f'{position_code}:{session_part}:v1',
                        'technical_spec_sections': ['5.5', '6.1'],
                    },
                    'is_deleted': False,
                    'deleted_at': None,
                },
            )
            templates[(position.id, session_part)] = template

    completed_sessions = Session.objects.filter(status='completed', is_deleted=False)
    for session in completed_sessions.iterator():
        template = templates.get((session.curriculum_position_id, session.intervention_part))
        if template and session.session_template_id is None:
            Session.objects.filter(pk=session.pk).update(session_template_id=template.id)

        references = []
        for section_code, item_set in (session.item_sets or {}).items():
            if not isinstance(item_set, dict):
                continue
            for item in item_set.get('items', []):
                if not isinstance(item, dict):
                    continue
                references.append(
                    {
                        'section_code': section_code,
                        'item_set_id': item_set.get('item_set_id'),
                        **{
                            key: item[key]
                            for key in (
                                'item_id',
                                'position_code',
                                'correct',
                                'mode',
                                'prompt_level',
                                'latency_seconds',
                                'timeout',
                                'response_rating',
                            )
                            if key in item
                        },
                    }
                )
        ratings = [
            item['response_rating']
            for item in references
            if isinstance(item.get('response_rating'), int) and 1 <= item['response_rating'] <= 5
        ]
        error_tags = list(
            dict.fromkeys(
                pattern['code']
                for pattern in (session.error_patterns or [])
                if isinstance(pattern, dict) and pattern.get('code')
            )
        )
        SkillObservation.objects.update_or_create(
            session_id=session.id,
            curriculum_position_id=session.curriculum_position_id,
            defaults={
                'center_id': session.center_id,
                'child_id': session.child_id,
                'accuracy_rate': session.accuracy_rate,
                'response_rating': round(sum(ratings) / len(ratings)) if ratings else None,
                'error_pattern_tags': error_tags,
                'time_signals': session.time_to_mastery_signals or {},
                'activities': session.activities_completed or [],
                'item_references': references,
                'source_session_revision': session.revision,
                'metadata': {
                    'source': 'session_structured_capture_backfill',
                    'intervention_part': session.intervention_part,
                    'session_template_id': template.id if template else None,
                },
                'created_by_id': session.created_by_id,
                'updated_by_id': session.updated_by_id or session.created_by_id,
                'is_deleted': False,
                'deleted_at': None,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0006_placementrecommendation_final_curriculum'),
        ('intervention_sessions', '0002_session_accuracy_denominator_and_more'),
        ('schools', '0002_initial'),
        ('users', '0002_childprofile_availability_windows_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('session_part', models.CharField(choices=[('pfr_1a', 'PFR Session 1a'), ('pfr_1b', 'PFR Session 1b'), ('og_concept', 'OG+ Concept Session')], db_index=True, max_length=20)),
                ('capture_fields', models.JSONField(default=dict, help_text='JSON schema for the structured fields shown and required by this session form.')),
                ('title', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_templates', to='curriculum.curriculum')),
                ('curriculum_position', models.ForeignKey(blank=True, help_text='Optional lesson or concept this capture contract is specific to.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='session_templates', to='curriculum.curriculumsequence')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['curriculum', 'session_part', '-version', 'curriculum_position_id'],
            },
        ),
        migrations.AddField(
            model_name='session',
            name='session_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='intervention_sessions.sessiontemplate'),
        ),
        migrations.CreateModel(
            name='SkillObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('accuracy_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('response_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('error_pattern_tags', models.JSONField(blank=True, default=list)),
                ('time_signals', models.JSONField(blank=True, default=dict)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('item_references', models.JSONField(blank=True, default=list)),
                ('source_session_revision', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_records', to='schools.school')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_observations', to='users.childprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
                ('curriculum_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_observations', to='curriculum.curriculumsequence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_observations', to='intervention_sessions.session')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(app_label)s_%(class)s_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-session__scheduled_start', 'curriculum_position__sequence_order'],
            },
        ),
        migrations.AddIndex(
            model_name='sessiontemplate',
            index=models.Index(fields=['center', 'curriculum', 'session_part', 'is_active'], name='interventio_center__192c22_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontemplate',
            index=models.Index(fields=['curriculum_position', 'session_part', 'is_active'], name='interventio_curricu_b3918f_idx'),
        ),
        migrations.AddIndex(
            model_name='sessiontemplate',
            index=models.Index(fields=['is_deleted', 'created_at'], name='interventio_is_dele_e0ecb4_idx'),
        ),
        migrations.AddConstraint(
            model_name='sessiontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_position__isnull', False)), fields=('center', 'curriculum', 'curriculum_position', 'session_part', 'version'), name='unique_position_session_template_version'),
        ),
        migrations.AddConstraint(
            model_name='sessiontemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('curriculum_position__isnull', True)), fields=('center', 'curriculum', 'session_part', 'version'), name='unique_generic_session_template_version'),
        ),
        migrations.AddIndex(
            model_name='skillobservation',
            index=models.Index(fields=['center', 'child'], name='interventio_center__9f6f97_idx'),
        ),
        migrations.AddIndex(
            model_name='skillobservation',
            index=models.Index(fields=['child', 'curriculum_position'], name='interventio_child_i_f6889d_idx'),
        ),
        migrations.AddIndex(
            model_name='skillobservation',
            index=models.Index(fields=['session', 'curriculum_position'], name='interventio_session_ba7a19_idx'),
        ),
        migrations.AddIndex(
            model_name='skillobservation',
            index=models.Index(fields=['center', 'created_at'], name='interventio_center__8fca0f_idx'),
        ),
        migrations.AddIndex(
            model_name='skillobservation',
            index=models.Index(fields=['is_deleted', 'created_at'], name='interventio_is_dele_0b1952_idx'),
        ),
        migrations.AddConstraint(
            model_name='skillobservation',
            constraint=models.UniqueConstraint(fields=('session', 'curriculum_position'), name='unique_session_skill_observation'),
        ),
        migrations.RunPython(seed_templates_and_observations, migrations.RunPython.noop),
    ]
