# Generated by Django 5.1.15 on 2026-07-24 18:29

import uuid
from django.db import migrations, models


def populate_client_request_ids(apps, schema_editor):
    Session = apps.get_model("intervention_sessions", "Session")
    for session in Session.objects.filter(client_request_id__isnull=True).iterator():
        session.client_request_id = uuid.uuid4()
        session.save(update_fields=["client_request_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('intervention_sessions', '0003_sessiontemplate_session_session_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='client_request_id',
            field=models.UUIDField(blank=True, editable=False, help_text='Client-generated idempotency key for safe mobile retries.', null=True),
        ),
        migrations.RunPython(populate_client_request_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='session',
            name='client_request_id',
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text='Client-generated idempotency key for safe mobile retries.',
                unique=True,
            ),
        ),
    ]
