# Generated by Django 5.2.17 on 2026-10-01 23:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=16, unique=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('connected', 'Connected'), ('reconnect', 'Reconnect required')], default='disconnected', max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('encrypted_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('via_facebook', models.BooleanField(default=False)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('connected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_accounts_connected', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['network'],
            },
        ),
        migrations.CreateModel(
            name='SocialAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('session_hash', models.CharField(max_length=64)),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=16)),
                ('code_used', models.BooleanField(default=False)),
                ('consumed', models.BooleanField(default=False)),
                ('awaiting_choice', models.BooleanField(default=False)),
                ('encrypted_choices', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_authorizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brief', models.TextField(blank=True)),
                ('audience', models.CharField(choices=[('families', 'Families'), ('teachers', 'Teachers'), ('general', 'General')], default='families', max_length=16)),
                ('tone', models.CharField(choices=[('warm', 'Warm'), ('practical', 'Practical'), ('celebratory', 'Celebratory')], default='warm', max_length=16)),
                ('facebook_caption', models.TextField(blank=True)),
                ('instagram_caption', models.TextField(blank=True)),
                ('link_url', models.URLField(blank=True)),
                ('image_data', models.BinaryField(blank=True, null=True)),
                ('image_content_type', models.CharField(blank=True, max_length=80)),
                ('image_name', models.CharField(blank=True, max_length=200)),
                ('post_to_facebook', models.BooleanField(default=True)),
                ('post_to_instagram', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('posted', 'Posted'), ('attention', 'Needs attention')], db_index=True, default='draft', max_length=16)),
                ('source', models.CharField(choices=[('brief', 'From a brief'), ('manual', 'Written by hand')], default='manual', max_length=16)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram')], max_length=16)),
                ('status', models.CharField(choices=[('published', 'Published'), ('failed', 'Failed')], max_length=16)),
                ('external_id', models.CharField(blank=True, max_length=64)),
                ('permalink', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='social.socialpost')),
            ],
            options={
                'ordering': ['network'],
                'constraints': [models.UniqueConstraint(fields=('post', 'network'), name='social_publication_once_per_network')],
            },
        ),
    ]
