# Generated by Django 5.2.17 on 2026-10-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social", "0001_initial_social_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("week_of", models.DateField(unique=True)),
                ("planned_at", models.DateTimeField()),
                ("pillar", models.CharField(max_length=40)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Preparing"),
                            ("generating", "Generating"),
                            ("ready", "Ready"),
                            ("held", "Needs review"),
                            ("error", "Generation failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("context", models.JSONField(default=dict)),
                ("content", models.JSONField(default=dict)),
                ("auto_scheduled", models.BooleanField(default=False)),
                ("review_passed", models.BooleanField(default=False)),
                ("review_note", models.CharField(blank=True, max_length=500)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "post",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="content_week",
                        to="social.socialpost",
                    ),
                ),
            ],
            options={
                "ordering": ["planned_at"],
            },
        ),
        migrations.CreateModel(
            name="ContentPlan",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("paused", "Paused"),
                            ("review", "Review first"),
                            ("automatic", "Automatic"),
                        ],
                        default="paused",
                        max_length=16,
                    ),
                ),
                ("weekday", models.PositiveSmallIntegerField(default=1)),
                ("posting_hour", models.PositiveSmallIntegerField(default=10)),
                (
                    "audience",
                    models.CharField(
                        choices=[
                            ("families", "Families"),
                            ("teachers", "Teachers"),
                            ("general", "General"),
                        ],
                        default="families",
                        max_length=20,
                    ),
                ),
                ("priorities", models.TextField(blank=True, max_length=2000)),
                ("post_to_facebook", models.BooleanField(default=True)),
                ("post_to_instagram", models.BooleanField(default=True)),
                ("preview_requested", models.BooleanField(default=False)),
                ("last_worker_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=300)),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("pk", 1)), name="social_single_content_plan"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("weekday__lte", 6)),
                        name="social_plan_weekday",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("posting_hour__gte", 8), ("posting_hour__lte", 20)
                        ),
                        name="social_plan_daytime",
                    ),
                ],
            },
        ),
    ]
