# Generated by Django 5.2.17 on 2026-10-03 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcontentweek_blogcontentplan'),
        ('social', '0002_contentweek_contentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='blog_auto_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='blog_post',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facebook_promotion', to='blog.blogpost'),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='blog_publication_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='source',
            field=models.CharField(choices=[('brief', 'From a brief'), ('manual', 'Written by hand'), ('blog', 'Blog feature')], default='manual', max_length=16),
        ),
    ]
